/* Role-aware student profile viewer used outside the Admin workspace. */
const RoleProfileViewer=(()=>{
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  let context=null,activeTab='overview';
  function ensureHost(){
    let host=document.getElementById('roleProfileOverlay');
    if(host)return host;
    host=document.createElement('div');host.id='roleProfileOverlay';host.className='role-profile-overlay';host.setAttribute('role','dialog');host.setAttribute('aria-modal','true');host.setAttribute('aria-label','Student profile');host.addEventListener('click',event=>{if(event.target===host)close()});document.body.appendChild(host);return host;
  }
  function data(){return{students:DB.read('students',[]),faculty:DB.read('faculty',[]),subjects:DB.read('subjects',[]),enrollments:DB.read('studentEnrollments',[]),allotments:DB.read('allotments',[]),sectionSubjects:DB.read('sectionSubjects',[]),exams:DB.read('exams',[]),submissions:DB.read('studentSubmissions',[]),audit:DB.read('applicationAuditLog',[])};}
  function relevant(d,student){
    const enrollment=d.enrollments.filter(item=>item.studentId===student.id&&(!context.subjectCode||item.subjectCode===context.subjectCode)&&(!context.sectionId||item.sectionId===context.sectionId));
    if(enrollment.length)return enrollment;
    return d.allotments.filter(item=>item.studentId===student.id&&(!context.subjectCode||item.subjectCode===context.subjectCode)&&(!context.viewerId||context.viewerRole!=='faculty'||item.facultyId===context.viewerId)).map(item=>({studentId:item.studentId,subjectCode:item.subjectCode,sectionId:context.sectionId||(student.sections||[])[0]||'Legacy section'}));
  }
  function renderFaculty(d,student,enrollment){
    const examIds=new Set(d.exams.filter(exam=>exam.facultyId===context.viewerId&&(!context.subjectCode||exam.subjectCode===context.subjectCode)).map(exam=>exam.id));
    const submissions=d.submissions.filter(item=>item.studentId===student.id&&examIds.has(item.examId));
    if(activeTab==='grades')return `<div class="role-profile-table"><table><thead><tr><th>Examination</th><th>Submitted</th><th>Score</th><th>Status</th></tr></thead><tbody>${submissions.map(item=>{const exam=d.exams.find(x=>x.id===item.examId),score=Number(item.score??(item.answers||[]).reduce((sum,a)=>sum+(Number(a.awarded)||0),0)),total=Number(item.total)||0,pct=total?Math.round(score/total*100):0;return `<tr><td>${esc(exam?.title||item.examId)}</td><td>${esc(item.submittedAt?new Date(item.submittedAt).toLocaleString():'—')}</td><td>${score}/${total} · ${pct}%</td><td>${pct>=(exam?.passingPercent||75)?'Passed':'Failed'}</td></tr>`}).join('')||'<tr><td colspan="4">No submissions for your examinations.</td></tr>'}</tbody></table></div>`;
    if(activeTab==='activity'){const logs=d.audit.filter(item=>item.actorId===student.id&&(examIds.has(item.entityId)||examIds.has(item.details?.examId)));return `<div class="role-profile-table"><table><thead><tr><th>Activity</th><th>Record</th><th>Date</th></tr></thead><tbody>${logs.map(item=>`<tr><td>${esc(item.action)}</td><td>${esc(item.entityType)} ${esc(item.entityId||'')}</td><td>${esc(new Date(item.at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="3">No relevant activity recorded.</td></tr>'}</tbody></table></div>`;}
    const subjects=[...new Set(enrollment.map(item=>item.subjectCode))],sections=[...new Set(enrollment.map(item=>item.sectionId))];
    return `<div class="role-profile-stats"><div><strong>${subjects.length}</strong><span>Relevant subjects</span></div><div><strong>${sections.length}</strong><span>Sections</span></div><div><strong>${submissions.length}</strong><span>Attempts</span></div></div><div class="role-profile-columns"><section><h3>Enrollment</h3>${enrollment.map(item=>`<div class="role-profile-row"><strong>${esc(item.subjectCode)}</strong><span>${esc(item.sectionId)}</span></div>`).join('')||'<p>No matching enrollment.</p>'}</section><section><h3>Privacy scope</h3><p>Only records connected to subjects and examinations handled by you are shown.</p></section></div>`;
  }
  function renderStudent(d,student,enrollment){const subjects=[...new Set(enrollment.map(item=>item.subjectCode))],sections=[...new Set(enrollment.map(item=>item.sectionId))];return `<div class="role-profile-public"><h3>Shared class information</h3><p>You and ${esc(student.first)} share the following current class context.</p><div class="role-profile-tags">${subjects.map(code=>`<span>${esc(code)}</span>`).join('')}${sections.map(id=>`<span>${esc(id)}</span>`).join('')}</div><div class="role-profile-privacy">Grades, submissions, activity, login details, credentials, and other private information are hidden from fellow students.</div></div>`;}
  function render(){const host=ensureHost(),d=data(),student=d.students.find(item=>item.id===context.studentId);if(!student){close();return}const enrollment=relevant(d,student),facultyView=context.viewerRole==='faculty';const initials=`${student.first?.[0]||''}${student.last?.[0]||''}`.toUpperCase();host.innerHTML=`<article class="role-profile-page"><header class="role-profile-head"><div class="role-profile-avatar">${esc(initials)}</div><div><small>${facultyView?'Student academic profile':'Classmate profile'}</small><h2>${esc(student.first)} ${esc(student.last)}</h2>${facultyView?`<p>${esc(student.id)} · ${esc([...new Set(enrollment.map(item=>item.sectionId))].join(', ')||'No matching section')}</p>`:'<p>Limited public information</p>'}</div><button type="button" class="role-profile-close" onclick="RoleProfileViewer.close()" aria-label="Close profile">×</button></header>${facultyView?`<nav class="role-profile-tabs" aria-label="Student profile sections">${[['overview','Overview'],['grades','Grades'],['activity','Activity']].map(([id,label])=>`<button class="${activeTab===id?'active':''}" onclick="RoleProfileViewer.tab('${id}')">${label}</button>`).join('')}</nav>`:''}<main class="role-profile-content">${facultyView?renderFaculty(d,student,enrollment):renderStudent(d,student,enrollment)}</main></article>`;host.classList.add('open');document.body.classList.add('profile-view-open');host.querySelector('.role-profile-close')?.focus();}
  function openStudent(studentId,options={}){const session=DB.read('currentUser',null)||{};context={studentId,viewerRole:options.viewerRole||session.role,viewerId:options.viewerId||session.username,subjectCode:options.subjectCode||'',sectionId:options.sectionId||''};const d=data(),student=d.students.find(item=>item.id===studentId);if(!student)return;const matches=relevant(d,student);if(context.viewerRole==='faculty'&&!matches.length)return;if(context.viewerRole==='student'){const viewer=d.students.find(item=>item.id===context.viewerId),viewerMatches=viewer?relevant(d,viewer):[];const shared=matches.some(a=>viewerMatches.some(b=>a.subjectCode===b.subjectCode&&a.sectionId===b.sectionId));if(!shared)return;}activeTab='overview';render();}
  function tab(name){if(!['overview','grades','activity'].includes(name))return;activeTab=name;render();}
  function close(){document.getElementById('roleProfileOverlay')?.classList.remove('open');document.body.classList.remove('profile-view-open');}
  return{openStudent,tab,close};
})();
window.RoleProfileViewer=RoleProfileViewer;
