const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== ADMIN DASHBOARD CARDS. Direct, accessible list navigation ===');
const r=load('admin.html',{...SEED(),currentUser:{username:'admin',role:'admin'}});
ok(!!r.d.querySelector('.site-status-panel')&&/CSV \+ browser storage/.test(r.d.querySelector('.site-status-panel').textContent),'dashboard shows an honest local prototype status panel');
ok(!r.d.getElementById('siteStatusTitle')&&r.d.querySelector('.site-status-panel').getAttribute('aria-label')==='Site status','status cells no longer repeat a visible heading block');
ok(r.d.querySelectorAll('.monitor-card').length===3&&/Interface response/.test(r.d.querySelector('.dashboard-monitoring').textContent),'dashboard shows three real client-side monitoring charts');
ok(r.d.getElementById('responseLine').getAttribute('points').length>0&&/records/.test(r.d.getElementById('metricRecords').textContent),'monitoring charts receive measured browser data');
ok(r.d.querySelectorAll('.dashboard-view-btn').length===2,'dashboard offers grid and list views');
ok(r.d.querySelector('.dashboard-card-toolbar').nextElementSibling.classList.contains('card-grid'),'view switch sits directly before the management cards');
ok(r.d.querySelectorAll('.monitor-control').length===3,'monitoring has Start, Restart, and Stop controls');
r.w.stopMonitoring();
ok(/Paused/.test(r.d.getElementById('monitoringState').textContent)&&!r.d.getElementById('monitorStart').disabled&&r.d.getElementById('monitorStop').disabled,'Stop pauses sampling and updates its controls');
r.w.startMonitoring();
ok(/Live/.test(r.d.getElementById('monitoringState').textContent)&&r.d.getElementById('monitorStart').disabled&&!r.d.getElementById('monitorStop').disabled,'Start resumes live sampling');
r.w.setDashboardView('list');
ok(r.d.getElementById('dashboardSection').classList.contains('dashboard-view-list')&&r.w.localStorage.getItem('adminDashboardView:admin')==='list','list view applies and is saved for the Admin account');
const cards=[...r.d.querySelectorAll('.admin-dashboard-link')];
ok(cards.length===6,'all six dashboard cards are navigation shortcuts');
ok(cards.every(card=>card.tabIndex===0&&card.getAttribute('role')==='link'&&card.getAttribute('aria-label')),'cards are keyboard accessible and named');
cards[1].dispatchEvent(new r.w.MouseEvent('click',{bubbles:true}));
ok(r.d.getElementById('studentSection').style.display==='block','clicking Students opens its management page');
ok(r.d.getElementById('studentTable').textContent.includes('S1'),'destination shows the student list');
ok(r.w.getComputedStyle(r.d.getElementById('dashboardSection')).display==='none','Dashboard overview and monitoring are not visually persistent on management pages');
ok(/Paused/.test(r.d.getElementById('monitoringState').textContent),'monitoring pauses while the Dashboard page is not selected');
r.w.showSection('dashboardSection');
ok(r.d.getElementById('dashboardSection').style.display==='block'&&/Live/.test(r.d.getElementById('monitoringState').textContent),'returning to Dashboard restores its page and live monitoring');
cards[2].dispatchEvent(new r.w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
ok(r.d.getElementById('subjectSection').style.display==='block','Enter on Subjects opens its management page');
ok(r.d.getElementById('subjectTable').textContent.includes('SUB1'),'destination shows the subject list');
r.w.showSection('dashboardSection');
cards[0].querySelector('.plus-circle').click();
ok(r.d.getElementById('dashboardSection').style.display==='block','plus action does not navigate away from Dashboard');
ok(r.d.getElementById('facultyModal').style.display==='flex','plus action still opens its form');
r.w.close(); process.exit(0);
