const fs=require('fs');
const path=require('path');
const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);

console.log('=== ADMIN MODERN UI. Calm cards and accessible icon actions ===');
const html=fs.readFileSync(path.join(__dirname,'..','html','admin.html'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'..','css','admin-modern.css'),'utf8');
ok(/admin-modern\.css/.test(html),'Admin loads a dedicated visual layer');
ok(/repeat\(5/.test(css) && /repeat\(3/.test(css) && /repeat\(2/.test(css),'metric grid adapts across desktop, tablet, and mobile');
ok(/background: #fff !important/.test(css),'legacy multicolor card surfaces are overridden with neutral surfaces');
ok(/table-icon-btn/.test(css) && /focus-visible/.test(css),'icon actions include hover and keyboard focus treatments');
const r=load('admin.html',{...SEED(),currentUser:{username:'admin',role:'admin'}});
const actions=[...r.d.querySelectorAll('#facultyTable .admin-row-action')];
ok(actions.length>0&&actions.length===r.d.querySelectorAll('#facultyTable tr').length-1,'each Faculty row uses one compact settings action');
ok(actions.every(action=>/Edit/.test(action.textContent)&&/Delete/.test(action.textContent)),'each Faculty settings menu names Edit and Delete');
const triggers=actions.map(action=>action.querySelector('.section-action-trigger'));
ok(triggers.every(button=>button.querySelector('svg')),'row actions use scalable SVG icons');
ok(triggers.every(button=>button.getAttribute('aria-label') && button.title),'icons retain accessible names and tooltips');
const firstFacultyCell=r.d.querySelector('#facultyTable tr:nth-child(2) td');
firstFacultyCell.dispatchEvent(new r.w.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:80,clientY:90}));
ok(firstFacultyCell.closest('tr').querySelector('.section-action-menu').classList.contains('open'),'right-clicking a table cell opens its settings menu');
ok(r.d.querySelectorAll('.plus-circle').length===5 && [...r.d.querySelectorAll('.plus-circle')].every(button=>button.tagName==='BUTTON'),'dashboard add actions use semantic buttons');
ok(/\.student-profile-page[^}]*height:calc\(100dvh - 36px\)[^}]*overflow-y:auto/.test(css),'profile page has a viewport-bound vertical scroll region');
r.w.close();
process.exit(0);
