const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== CROSS-ROLE TABLE TOOLS. Admin, Faculty, and Student ===');
let seed=SEED();
seed.allotments.push({studentId:'S1',subjectCode:'SUB2',facultyId:'F2'});
let r=load('student.html',{...seed,currentUser:{username:'S1',role:'student'}});
ok(r.d.querySelectorAll('.role-table-tools .table-tools').length===3,'Student exams, results, and subjects have table tools');
const subjectTools=r.d.querySelector('[data-table-tools="student-subjects"]');
subjectTools.querySelector('.table-search-toggle').click(); const input=subjectTools.querySelector('input[type="search"]'); input.value='HCI'; input.dispatchEvent(new r.w.Event('input',{bubbles:true}));
ok(/HCI/.test(r.d.getElementById('subjectsTable').textContent),'Student can search subjects');
ok([...r.d.querySelectorAll('#studentSubjectCards .enrolled-subject-card')].filter(card=>!card.hidden).length===1,'Student search filters the visible subject cards');
input.value='';input.dispatchEvent(new r.w.Event('input',{bubbles:true}));
const direction=subjectTools.querySelector('.table-direction');direction.click();
ok(r.d.querySelector('#studentSubjectCards .enrolled-subject-card')?.dataset.subject==='SUB2','direction control reverses the visible card order');
ok(!subjectTools.querySelector('.table-group-toggle')&&!subjectTools.querySelector('.group-field'),'Enrolled Subjects omits inapplicable grouping');
r.w.close();

seed=SEED(); seed.students.push({id:'S2',last:'Zulu',first:'Ana',sections:['A']}); seed.studentSubmissions=[{id:'sub2',studentId:'S2',examId:'e1',submittedAt:'2026-08-20T09:00:00Z',total:10,answers:[{awarded:7,needsManualGrading:false}]},{id:'sub-old',studentId:'S1',examId:'e1',submittedAt:'2026-08-19T10:00:00Z',total:10,answers:[{awarded:6,needsManualGrading:false}]},{id:'sub1',studentId:'S1',examId:'e1',submittedAt:'2026-08-20T10:00:00Z',total:10,answers:[{awarded:8,needsManualGrading:false}]}];
r=load('faculty.html',{...seed,currentUser:{username:'F1',role:'faculty'}});
r.w.viewResults('e1');
ok(!!r.d.querySelector('[data-table-tools="faculty-results"]'),'Faculty examination results have the same tools');
ok(!!r.d.querySelector('#facultyResultTools .table-sort-toggle')&&!r.d.querySelector('#facultyResultTools .table-group-toggle'),'Faculty results keep search and sorting while omitting inapplicable grouping');
ok(r.d.querySelectorAll('#facultyResultsTable tr').length===3,'Faculty results show one latest record per student instead of every attempt');
const resultSort=r.d.querySelector('#facultyResultTools .sort-field select');resultSort.value='1';resultSort.dispatchEvent(new r.w.Event('change',{bubbles:true}));
ok(/Cruz/.test(r.d.querySelector('#facultyResultsTable tr:nth-child(2)').textContent),'Faculty result sorting reorders rows by the selected field');
r.d.querySelector('#facultyResultTools .table-direction').click();
ok(/Zulu/.test(r.d.querySelector('#facultyResultsTable tr:nth-child(2)').textContent),'Ascending and descending control transforms the result order');
r.w.close(); process.exit(0);
