const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== APPLICATION AUDIT. Sign-ins and staff changes ===');
let seed=SEED();
let r=load('login.html',seed,{query:'?role=admin'});
r.d.getElementById('username').value='admin'; r.d.getElementById('password').value='a';
r.d.getElementById('loginForm').dispatchEvent(new r.w.Event('submit',{bubbles:true,cancelable:true}));
ok(r.read('applicationAuditLog').some(entry=>entry.action==='login'&&entry.actorId==='admin'),'successful login records the actor and role'); r.w.close();

seed=SEED(); seed.sections=[{id:'A',name:'A'}]; seed.sectionSubjects=[{sectionId:'A',subjectCodes:['SUB1']}];
seed.students.push({id:'S2',last:'Reyes',first:'Ana',sections:['A']});
seed.studentSubmissions=[{id:'x',studentId:'S1',examId:'e1',total:10,answers:[]}];
r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
ok(!r.d.getElementById('allotmentSection'),'Student–Subject Allotment page is removed');
ok(![...r.d.querySelectorAll('#sidebar a')].some(link=>/Student.Subject Allotment/.test(link.textContent)),'removed page is absent from navigation');
r.d.getElementById('fID').value='99-99999-999'; r.d.getElementById('fLast').value='Audit'; r.d.getElementById('fFirst').value='Professor'; r.w.saveItem('faculty');
ok(r.read('applicationAuditLog').some(entry=>entry.action==='create'&&entry.entityType==='faculty'&&entry.actorId==='admin'),'Admin creation records who changed what');
ok(!!r.d.getElementById('auditTable'),'Audit page provides the filtered activity table');
ok(r.d.querySelector('#auditTableTools [data-table-tools="audit"]'),'Audit table retains its management tools');
ok(!r.d.getElementById('auditExam')&&!r.d.getElementById('participationSummary'),'Exam participation controls and summary are removed');
ok(!r.d.getElementById('auditTaken')&&!r.d.getElementById('auditNotTaken'),'Took and did-not-take student lists are removed');
ok(/authentication, access, lifecycle, permissions/.test(r.d.querySelector('#auditSection .panel-help').textContent),'Audit page explains its complete operational scope');
const filterIds=['auditFrom','auditTo','auditActor','auditRole','auditCategory','auditAction','auditTargetType','auditTargetId','auditResult'];
ok(filterIds.every(id=>r.d.getElementById(id)),'Admin audit provides date, actor, role, category, action, target, and result filters');
ok(r.d.querySelectorAll('#auditCategory option').length===11,'category filter exposes all ten required audit categories plus All');
r.w.eval("AuditLog.record('apply-failed','approval-request','APR-FAILED',{reason:'Stale target'},{username:'dean.demo',role:'dean'},{category:'approval',result:'failed',reason:'Stale target'})");
r.w.renderAuditLog();
r.d.getElementById('auditCategory').value='approval';r.d.getElementById('auditCategory').dispatchEvent(new r.w.Event('change'));
ok(r.d.getElementById('auditTable').textContent.includes('APR-FAILED')&&!r.d.getElementById('auditTable').textContent.includes('99-99999-999'),'category filter limits the visible audit events');
r.d.getElementById('auditResult').value='failed';r.d.getElementById('auditResult').dispatchEvent(new r.w.Event('change'));
ok(/failed/.test(r.d.getElementById('auditTable').textContent)&&/Stale target/.test(r.d.getElementById('auditTable').textContent),'result filter retains failure reason and target details');
r.d.getElementById('auditTargetId').value='missing';r.d.getElementById('auditTargetId').dispatchEvent(new r.w.Event('input'));
ok(/No audit events match/.test(r.d.getElementById('auditTable').textContent),'target ID filter provides a clear empty state');
r.w.resetAuditFilters();
ok(r.d.getElementById('auditTable').textContent.includes('99-99999-999')&&/Showing \d+ of \d+ audit events/.test(r.d.getElementById('auditFilterSummary').textContent),'Reset restores the complete Admin audit view and summary');
r.w.close(); process.exit(0);
