const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== APPLICATION AUDIT. Sign-ins and staff changes ===');
let seed=SEED();
let r=load('login.html',seed,{query:'?role=admin'});
r.d.getElementById('username').value='admin'; r.d.getElementById('password').value='a';
r.d.getElementById('loginForm').dispatchEvent(new r.w.Event('submit',{bubbles:true,cancelable:true}));
ok(r.read('applicationAuditLog').some(entry=>entry.action==='login'&&entry.actorId==='admin'),'successful login records the actor and role'); r.w.close();

seed=SEED(); seed.sections=[{id:'A',name:'A'}]; seed.sectionSubjects=[{sectionId:'A',subjectCodes:['SUB1']}];
seed.students.push({id:'S2',last:'Reyes',first:'Ana',sections:['A']});
seed.studentSubmissions=[{id:'x',studentId:'S1',examId:'e1',total:10,answers:[]}];
r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
ok(!r.d.getElementById('allotmentSection'),'Student–Subject Allotment page is removed');
ok(![...r.d.querySelectorAll('#sidebar a')].some(link=>/Student.Subject Allotment/.test(link.textContent)),'removed page is absent from navigation');
r.d.getElementById('subCode').value='AUD1'; r.d.getElementById('subName').value='Audit Subject'; r.w.saveItem('subjects');
ok(r.read('applicationAuditLog').some(entry=>entry.action==='create'&&entry.entityType==='subject'&&entry.actorId==='admin'),'Admin creation records who changed what');
ok(!!r.d.getElementById('auditTable'),'Audit page provides the filtered activity table');
ok(r.d.querySelector('#auditTableTools [data-table-tools="audit"]'),'Audit table retains its management tools');
ok(!r.d.getElementById('auditExam')&&!r.d.getElementById('participationSummary'),'Exam participation controls and summary are removed');
ok(!r.d.getElementById('auditTaken')&&!r.d.getElementById('auditNotTaken'),'Took and did-not-take student lists are removed');
ok(/sign-in details/i.test(r.d.querySelector('#auditSection .panel-help').textContent),'Audit scope is sign-ins and staff changes');
ok([...r.d.querySelectorAll('.audit-tab')].map(button=>button.textContent.trim()).join('|')==='Professors|Admin|Log in','Audit activity is separated into Professors, Admin, and Log in tabs');
r.w.setAuditTab('admin');
ok(r.d.querySelector('[data-audit-tab="admin"]').getAttribute('aria-selected')==='true'&&r.d.getElementById('auditTable').textContent.includes('AUD1'),'Admin tab shows administrative changes');
r.w.setAuditTab('login');
ok(!r.d.getElementById('auditTable').textContent.includes('AUD1'),'Log in tab excludes change records');
r.w.close(); process.exit(0);
