const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);

(async()=>{
console.log('=== AUTHORING. Responsive workspace and settings inspector ===');
let s=SEED();
let r=load('faculty.html',{...s,currentUser:{username:'F1',role:'faculty'}});
r.w.manageQuestions('e1');
r.w.openQuestionModal();
const modal=r.d.getElementById('questionModal');
ok(modal.classList.contains('active'),'question workspace opens');
ok(!!modal.querySelector('.question-canvas'),'main question canvas present');
ok(!!modal.querySelector('.question-inspector'),'second-column inspector present');
ok(!!modal.querySelector('.authoring-mobile-bar'),'mobile bottom navigation present');
ok(!modal.classList.contains('inspector-open'),'canvas starts full width');
r.w.toggleQuestionInspector();
ok(modal.classList.contains('inspector-open'),'settings icon opens inspector');
ok(r.d.getElementById('questionSettingsBtn').getAttribute('aria-expanded')==='true','settings button exposes state');
r.w.closeQuestionInspector();
ok(!modal.classList.contains('inspector-open'),'inspector closes without closing editor');
ok(!!r.d.getElementById('questionInlinePreview'),'inline student preview present');

console.log('\n=== DRAFTS. Incomplete work autosaves separately and restores ===');
const text=r.d.getElementById('questionText');
text.value='Draft prompt';
text.dispatchEvent(new r.w.Event('input',{bubbles:true}));
ok(/Draft prompt/.test(r.d.getElementById('questionInlinePreview').textContent),'preview updates with the prompt');
r.d.querySelector('#optionsContainer input[type="text"]').value='Draft option';
r.d.querySelector('#optionsContainer input[type="text"]').dispatchEvent(new r.w.Event('input',{bubbles:true}));
ok(/Saving draft/.test(r.d.getElementById('questionDraftState').textContent),'visible saving state');
await new Promise(resolve=>setTimeout(resolve,600));
let drafts=r.read('questionDrafts');
ok(drafts['e1::new'].text==='Draft prompt','prompt saved as a draft');
ok(drafts['e1::new'].options[0].text==='Draft option','incomplete options saved without publishing');
ok(!(r.read('questions')||[]).some(q=>q.text==='Draft prompt'),'draft is not inserted into live questions');
r.w.closeQuestionModal();
r.w.openQuestionModal();
ok(r.d.getElementById('questionText').value==='Draft prompt','draft prompt restored after reopening');
ok(r.d.querySelector('#optionsContainer input[type="text"]').value==='Draft option','draft options restored');

console.log('\n=== TYPE SAFETY. Incompatible answer settings require confirmation ===');
const type=r.d.getElementById('questionType');
type.value='essay';
let typeChange=r.w.requestQuestionTypeChange('essay');
r.d.getElementById('confirmNo').click();
await typeChange;
ok(type.value==='mcq','cancel keeps the original question type');
typeChange=r.w.requestQuestionTypeChange('essay');
r.d.getElementById('confirmYes').click();
await typeChange;
ok(type.value==='essay','confirmed type change is applied');
type.value='mcq';
r.w.updateQuestionType();

console.log('\n=== COMMIT. Valid save clears the separate draft ===');
const options=[...r.d.querySelectorAll('#optionsContainer .option-input-group')];
options[0].querySelector('input[type="text"]').value='Yes';
options[1].querySelector('input[type="text"]').value='No';
options[0].querySelector('input[type="radio"]').checked=true;
r.w.saveQuestion();
ok((r.read('questions')||[]).some(q=>q.text==='Draft prompt'),'valid question committed to live collection');
ok(!r.read('questionDrafts')?.['e1::new'],'draft cleared after successful commit');
ok(!modal.classList.contains('active'),'workspace closes after successful save');
r.w.close();

console.log('\n=== EXAM SETTINGS. Exit choices and impact protection ===');
let s2=SEED();
s2.studentSubmissions=[{id:'sub1',examId:'e1',studentId:'S1'}];
let e=load('faculty.html',{...s2,currentUser:{username:'F1',role:'faculty'}});
e.w.editExam('e1');
const title=e.d.getElementById('examTitle');
title.value='Changed title';
title.dispatchEvent(new e.w.Event('input',{bubbles:true}));
let closing=e.w.closeExamModal();
e.d.getElementById('continueEditing').click();
await closing;
ok(e.d.getElementById('examModal').classList.contains('active'),'Continue Editing keeps the form open');
closing=e.w.closeExamModal();
e.d.getElementById('discardChanges').click();
await closing;
ok(!e.d.getElementById('examModal').classList.contains('active'),'Discard closes without saving');
ok(e.read('exams').find(x=>x.id==='e1').title==='F1 Exam','discard leaves stored exam unchanged');
e.w.editExam('e1');
const start=e.d.getElementById('examStart');
start.value='09:00';
start.dispatchEvent(new e.w.Event('change',{bubbles:true}));
let saving=e.w.saveExam();
ok(/1 existing submission/.test(e.d.getElementById('confirmMsg').textContent),'impact summary counts affected submissions');
e.d.getElementById('confirmNo').click();
await saving;
ok(e.read('exams').find(x=>x.id==='e1').start==='08:00','cancelled impact change is not saved');
saving=e.w.saveExam();
e.d.getElementById('confirmYes').click();
await saving;
ok(e.read('exams').find(x=>x.id==='e1').start==='09:00','confirmed impact change is saved');
e.w.close();
process.exit(0);
})();
