const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== FACULTY PROFILE. Relationships, performance, activity, and navigation ===');
const seed=SEED(); seed.sections=[{id:'A',name:'Section A'}]; seed.sectionSubjects=[{sectionId:'A',subjectCodes:['SUB1']}];
seed.studentSubmissions=[{id:'sub1',studentId:'S1',examId:'e1',submittedAt:'2026-08-20T10:00:00Z',total:10,answers:[{awarded:8,needsManualGrading:false}]}];
seed.applicationAuditLog=[{id:'a1',at:'2026-08-20T08:00:00Z',actorId:'F1',actorRole:'faculty',action:'login',entityType:'session',entityId:'F1'},{id:'a2',at:'2026-08-20T09:00:00Z',actorId:'F1',actorRole:'faculty',action:'create',entityType:'exam',entityId:'e1'}];
const r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
const row=r.d.querySelector('#facultyTable .profile-row');
ok(!!row&&row.tabIndex===0,'Faculty ID and name row is clickable and keyboard accessible');
row.querySelector('td').click();
ok(r.d.getElementById('facultyProfileName').textContent==='Maria Reyes','hero identifies the selected professor');
ok(r.d.getElementById('facultyProfileAvatar').textContent==='MR','faculty profile shows a circular initials avatar');
ok(/SUB1/.test(r.d.getElementById('facultyProfileContent').textContent)&&/Section A/.test(r.d.getElementById('facultyProfileContent').textContent),'overview shows subjects and their sections');
r.w.showFacultyProfileTab('performance');
ok(!!r.d.querySelector('.performance-track span')&&/average|No graded/.test(r.d.getElementById('facultyProfileContent').textContent),'section performance uses a bar graph and grading state');
r.w.showFacultyProfileTab('activity'); ok(/create/.test(r.d.getElementById('facultyProfileContent').textContent),'Actions tab shows Faculty activity');
r.w.showFacultyProfileTab('login'); ok(/Recorded logins/.test(r.d.getElementById('facultyProfileContent').textContent),'Login details show recorded sign-ins');
r.w.showFacultyProfileTab('overview'); r.d.querySelector('.profile-section-link').click();
ok(r.d.getElementById('sectionSection').style.display==='block','clicking a handled section opens Section Management');
ok(r.d.querySelector('#sectionTable tr.profile-target-row').textContent.includes('A'),'the selected Section row is highlighted');
r.w.close(); process.exit(0);
