const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);

console.log('=== FACULTY SUBJECT WORKSPACE. Course-level authoring and oversight ===');
let seed=SEED();
seed.sections=[{id:'A',name:'A',yearLevel:'1',program:'BSCS',sectionNumber:'1'}];
seed.sectionSubjects=[{sectionId:'A',assignments:[{subjectCode:'SUB1',facultyId:'F1'}]}];
seed.studentEnrollments=[{studentId:'S1',subjectCode:'SUB1',sectionId:'A'}];
let r=load('faculty.html',{...seed,currentUser:{username:'F1',role:'faculty'}});
ok(!!r.d.querySelector('#subjectList .sub-card[role="button"]'),'assigned subject card is clickable');
ok(!!r.d.querySelector('#subjectList .sub-course-icon svg')&&!!r.d.querySelector('#subjectList .sub-open-arrow svg'),'subject cards include a course icon and open affordance');
ok(r.d.querySelectorAll('#subjectList .sub-meta span').length>=2,'subject cards show section and exam counts');
ok(!r.d.querySelector('#subjectList .view-exams-btn')&&!/Open Subject/.test(r.d.getElementById('subjectList').textContent),'subject cards do not repeat a separate open button');
r.w.displayMyStudents();
ok(/My Students/.test(r.d.getElementById('studentsView').textContent)&&/Browse students enrolled/.test(r.d.getElementById('studentsView').textContent),'student roster has a page title and description');
ok(r.d.querySelectorAll('#studentsView .roster-tab-label').length===2,'subject and section tab rows have visible titles');
ok(/HCI/.test(r.d.querySelector('#studentsView .roster-subject-context')?.textContent||''),'selected subject name appears between subject and section tabs');
const rosterRow=r.d.querySelector('#studentsView .student-roster-table tbody tr[role="link"]');
ok(!!rosterRow,'every student roster row is a clickable profile link');
rosterRow?.click();
ok(r.d.getElementById('roleProfileOverlay')?.classList.contains('open')&&/Privacy scope/.test(r.d.getElementById('roleProfileOverlay').textContent),'Faculty opens a subject-scoped academic profile');
r.w.RoleProfileViewer?.close?.();
r.w.FacultySubjectWorkspace.open('SUB1');
ok(r.d.getElementById('subject-workspace-tab').style.display==='block','subject opens its own workspace page');
ok(r.d.querySelectorAll('.workspace-tab').length===4,'Main, Members, Grades, and Logs tabs are present');
ok(!r.d.querySelector('.workspace-rail'),'large student preview rail is removed');
ok(!!r.d.querySelector('.workspace-menu-trigger'),'hero uses a three-dot options menu');
r.d.querySelector('.workspace-menu-trigger').click();
ok(!/Go back|Preview A/.test(r.d.querySelector('.workspace-action-menu').textContent),'subject menu removes Go back and repeated section-specific preview actions');
ok(!!r.d.querySelector('.preview-subject-option')&&!!r.d.querySelector('.edit-subject-option'),'subject menu has concise icon-labelled Preview and Edit actions');
r.d.querySelector('.preview-subject-option').click();
ok(/Preview, which section\?/.test(r.d.querySelector('.preview-section-dialog').textContent),'Preview opens a section chooser prompt');
r.d.querySelector('.section-preview-option').click();
ok(r.d.getElementById('facultySubjectWorkspace').classList.contains('is-section-preview'),'section selection transforms the workspace into preview mode');
ok(/Section preview/.test(r.d.querySelector('.preview-banner').textContent),'preview identifies the selected section');
r.w.FacultySubjectWorkspace.openEditPrompt();
ok(r.d.querySelectorAll('.subject-edit-dialog [data-edit-action]').length===4,'Edit prompt offers color, icon, exam-rule cells, and hero description options with icons');
ok(!!r.d.querySelector('.subject-edit-dialog>.subject-dialog-close,.subject-edit-dialog>header>.subject-dialog-close'),'Edit prompt provides its dedicated top-right close control');
r.d.querySelector('.subject-edit-dialog [data-edit-action="color"]').click();
r.d.querySelector('.subject-color-options [data-color="#3576a8"]').click();
ok(r.read('subjects').find(item=>item.code==='SUB1').workspaceColor==='#3576a8','Edit color saves the subject accent');
r.w.FacultySubjectWorkspace.openEditPrompt();
r.d.querySelector('.subject-edit-dialog [data-edit-action="icon"]').click();
r.d.querySelector('.subject-icon-options [data-icon="code"]').click();
ok(r.read('subjects').find(item=>item.code==='SUB1').workspaceIcon==='code','Edit icon saves the selected subject icon');
r.w.FacultySubjectWorkspace.openEditPrompt();
r.d.querySelector('.subject-edit-dialog [data-edit-action="rules"]').click();
r.d.querySelector('.subject-rule-passing').value='80';
r.d.querySelector('.subject-rule-attempts').value='2';
r.d.querySelector('.subject-edit-save').click();
ok(r.read('exams').find(item=>item.id==='e1').passingPercent===80&&r.read('exams').find(item=>item.id==='e1').maxAttempts===2,'Edit cells saves the subject exam rules');
r.w.FacultySubjectWorkspace.openEditPrompt();
r.d.querySelector('.subject-edit-dialog [data-edit-action="description"]').click();
r.d.querySelector('.subject-description-input').value='A practical subject profile.';
r.d.querySelector('.subject-edit-save').click();
ok(r.read('subjects').find(item=>item.code==='SUB1').description==='A practical subject profile.','Hero profile description is saved');
r.w.FacultySubjectWorkspace.showTab('main');
ok(r.d.querySelectorAll('#workspaceBlockType option').length===3&&!/Markdown|Heading/.test(r.d.getElementById('workspaceBlockType').textContent),'weekly editor has one automatic text mode instead of separate Markdown and heading modes');
ok(r.d.querySelectorAll('.rich-text-toolbar button').length>=6,'weekly editor provides direct formatting controls');

r.d.getElementById('workspaceWeek').value='3';
r.d.getElementById('workspaceBlockTitle').value='Interaction Design';
r.d.getElementById('workspaceBlockBody').value='## Goals\n- Learn usability principles\n**Read carefully**';
r.w.FacultySubjectWorkspace.addBlock();
const content=r.read('subjectWorkspaceContent');
ok(content.some(item=>item.subjectCode==='SUB1'&&item.week===3&&item.title==='Interaction Design'),'weekly content cell autosaves');
ok(content.find(item=>item.title==='Interaction Design').collapsible===false&&r.d.querySelector('.student-content-block.always-open')?.open,'content stays expanded unless faculty explicitly enables collapsing');
ok(/Interaction Design/.test(r.d.querySelector('.week-stack').textContent),'saved cell appears in the selected week');
ok(!!r.d.querySelector('.content-block h2')&&!!r.d.querySelector('.content-block strong'),'Markdown headings and emphasis render inside cells');
ok(r.read('applicationAuditLog').some(item=>item.action==='add'&&item.entityType==='subject-content'),'content creation is audited');
ok(r.w.FacultySubjectWorkspace.attachExamToWeek(3,'e1'),'Faculty can attach an existing subject exam to a week');
ok(r.read('subjectWorkspaceContent').some(item=>item.week===3&&item.type==='exam'&&item.examId==='e1'),'weekly content stores an exam reference without moving the exam');
ok(!!r.d.querySelector('.week-stack .attached-exam-link'),'attached exam appears inside the selected week');
ok(!!r.d.querySelector('.faculty-exam-cell'),'the original exam cell remains in the Examinations section');
r.w.FacultySubjectWorkspace.renameWeek(3);
const weekEditor=r.d.querySelector('.enhanced-week-editor');
ok(!!weekEditor&&!!weekEditor.querySelector('.add-week-cell'),'Edit Week uses the matching editor and provides an Add cell icon');
const beforeCells=weekEditor.querySelectorAll('.week-editor-cell').length;
weekEditor.querySelector('.add-week-cell').click();
ok(weekEditor.querySelectorAll('.week-editor-cell').length===beforeCells+1,'Add cell creates another editable content cell');
const addedWeekCell=weekEditor.querySelector('.week-editor-cell:last-child');
ok(addedWeekCell.querySelectorAll('.week-cell-menu [data-cell-action]').length===3,'every Edit Week cell has a three-dot menu with move up, move down, and delete actions');
addedWeekCell.querySelector('[data-cell-action="up"]').click();
ok(!!addedWeekCell.nextElementSibling,'Move up changes the cell order');
addedWeekCell.querySelector('[data-cell-action="delete"]').click();
ok(weekEditor.querySelectorAll('.week-editor-cell').length===beforeCells,'Delete cell removes only the selected cell');
weekEditor.querySelector('.week-editor-close').click();

r.w.FacultySubjectWorkspace.showTab('members');
ok(/Prof\.|F1/.test(r.d.querySelector('.workspace-main').textContent),'Members lists faculty across the subject');
ok(!!r.d.querySelector('.workspace-table table')&&!!r.d.querySelector('.member-row'),'Members use a professor table');
r.d.querySelector('.member-row').click();
ok(!!r.d.querySelector('.member-section-table'),'Professor row expands to a handled-sections table');
r.w.FacultySubjectWorkspace.showTab('grades');
ok(!!r.d.querySelector('.workspace-grade-table table'),'Grades provides a section assessment table');
r.w.FacultySubjectWorkspace.showTab('logs');
ok([...r.d.querySelectorAll('.workspace-subtabs button')].some(button=>button.textContent.includes('Faculty')),'Logs provides a Faculty subtab');
ok([...r.d.querySelectorAll('.workspace-subtabs button')].some(button=>button.textContent.includes('Students')),'Logs provides a Students subtab');
r.w.FacultySubjectWorkspace.showTab('main');
const courseExamCell=r.d.querySelector('.faculty-exam-cell');
ok(!!courseExamCell&&!courseExamCell.querySelector('[aria-label="Open questions"]'),'Faculty Course Page removes the redundant Questions icon');
courseExamCell.click();
ok(/Question bank/.test(r.d.getElementById('examsView').textContent),'clicking the Faculty Course Page exam cell opens its question bank');
ok(r.d.getElementById('exams-tab').style.display==='block','Questions action navigates from the Course Page to the visible question bank page');
r.w.displayAllFacultyExams();
const listExamCell=r.d.querySelector('#examsView .exam-item[data-exam-id="e1"]');
ok(!!listExamCell&&!listExamCell.querySelector('.questions'),'Faculty exam lists use the exam cell instead of a redundant Questions icon');
listExamCell.click();
ok(/Question bank/.test(r.d.getElementById('examsView').textContent),'clicking a Faculty My Exams cell opens the selected question bank');
r.w.displayExamsBySubject('SUB1');
const subjectExamCell=r.d.querySelector('#examsView .exam-item[data-exam-id="e1"]');
subjectExamCell.click();
ok(/Question bank/.test(r.d.getElementById('examsView').textContent),'clicking an exam in a Faculty subject-filtered list opens its questions');
seed.subjectWorkspaceContent=r.read('subjectWorkspaceContent');
r.w.close();

let student=load('student.html',{...seed,currentUser:{username:'S1',role:'student'}});
student.w.openStudentSubject('SUB1');
ok(/Week 3/.test(student.d.getElementById('studentSubjectDetail').textContent),'Faculty weekly content appears on the real Student subject page');
ok(/Interaction Design/.test(student.d.getElementById('studentSubjectDetail').textContent),'Student sees the published content cell');
ok(student.d.querySelector('.learning-cell.always-open')?.open,'Student content is flat inside its week unless faculty enables collapsing');
const attachedExam=student.d.querySelector('#studentSubjectDetail .attached-exam-link');
ok(!!attachedExam,'Student sees the exam attached to the week');
attachedExam?.click();
ok(student.d.getElementById('takeExamModal').classList.contains('active'),'attached weekly exam opens the normal examination details prompt');
student.w.close();
process.exit(0);
