const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);

console.log('=== FACULTY SUBJECT WORKSPACE. Course-level authoring and oversight ===');
let seed=SEED();
seed.sections=[{id:'A',name:'A',yearLevel:'1',program:'BSCS',sectionNumber:'1'}];
seed.sectionSubjects=[{sectionId:'A',assignments:[{subjectCode:'SUB1',facultyId:'F1'}]}];
seed.studentEnrollments=[{studentId:'S1',subjectCode:'SUB1',sectionId:'A'}];
let r=load('faculty.html',{...seed,currentUser:{username:'F1',role:'faculty'}});
ok(!!r.d.querySelector('#subjectList .sub-card[role="button"]'),'assigned subject card is clickable');
ok(!!r.d.querySelector('#subjectList .sub-course-icon svg')&&!!r.d.querySelector('#subjectList .sub-open-arrow svg'),'subject cards include a course icon and open affordance');
ok(r.d.querySelectorAll('#subjectList .sub-meta span').length>=2,'subject cards show section and exam counts');
ok(!r.d.querySelector('#subjectList .view-exams-btn')&&!/Open Subject/.test(r.d.getElementById('subjectList').textContent),'subject cards do not repeat a separate open button');
r.w.displayMyStudents();
ok(/My Students/.test(r.d.getElementById('studentsView').textContent)&&/Browse students enrolled/.test(r.d.getElementById('studentsView').textContent),'student roster has a page title and description');
ok(r.d.querySelectorAll('#studentsView .roster-tab-label').length===2,'subject and section tab rows have visible titles');
ok(/HCI/.test(r.d.querySelector('#studentsView .roster-subject-context')?.textContent||''),'selected subject name appears between subject and section tabs');
const rosterRow=r.d.querySelector('#studentsView .student-roster-table tbody tr[role="link"]');
ok(!!rosterRow,'every student roster row is a clickable profile link');
rosterRow?.click();
ok(r.d.getElementById('roleProfileOverlay')?.classList.contains('open')&&/Privacy scope/.test(r.d.getElementById('roleProfileOverlay').textContent),'Faculty opens a subject-scoped academic profile');
r.w.RoleProfileViewer?.close?.();
r.w.FacultySubjectWorkspace.open('SUB1');
ok(r.d.getElementById('subject-workspace-tab').style.display==='block','subject opens its own workspace page');
ok(r.d.querySelectorAll('.workspace-tab').length===4,'Main, Members, Grades, and Logs tabs are present');
ok(!r.d.querySelector('.workspace-rail'),'large student preview rail is removed');
ok(!!r.d.querySelector('.workspace-menu-trigger'),'hero uses a three-dot options menu');
r.d.querySelector('.workspace-menu-trigger').click();
ok(r.d.querySelectorAll('.section-preview-option').length>0,'menu lists handled sections for preview');
r.d.querySelector('.section-preview-option').click();
ok(r.d.getElementById('facultySubjectWorkspace').classList.contains('is-section-preview'),'section selection transforms the workspace into preview mode');
ok(/Section preview/.test(r.d.querySelector('.preview-banner').textContent),'preview identifies the selected section');
r.w.FacultySubjectWorkspace.showTab('main');
ok(r.d.querySelectorAll('#workspaceBlockType option').length===3&&!/Markdown|Heading/.test(r.d.getElementById('workspaceBlockType').textContent),'weekly editor has one automatic text mode instead of separate Markdown and heading modes');
ok(r.d.querySelectorAll('.rich-text-toolbar button').length>=6,'weekly editor provides direct formatting controls');

r.d.getElementById('workspaceWeek').value='3';
r.d.getElementById('workspaceBlockTitle').value='Interaction Design';
r.d.getElementById('workspaceBlockBody').value='## Goals\n- Learn usability principles\n**Read carefully**';
r.w.FacultySubjectWorkspace.addBlock();
const content=r.read('subjectWorkspaceContent');
ok(content.some(item=>item.subjectCode==='SUB1'&&item.week===3&&item.title==='Interaction Design'),'weekly content cell autosaves');
ok(content.find(item=>item.title==='Interaction Design').collapsible===false&&r.d.querySelector('.student-content-block.always-open')?.open,'content stays expanded unless faculty explicitly enables collapsing');
ok(/Interaction Design/.test(r.d.querySelector('.week-stack').textContent),'saved cell appears in the selected week');
ok(!!r.d.querySelector('.content-block h2')&&!!r.d.querySelector('.content-block strong'),'Markdown headings and emphasis render inside cells');
ok(r.read('applicationAuditLog').some(item=>item.action==='add'&&item.entityType==='subject-content'),'content creation is audited');
ok(r.w.FacultySubjectWorkspace.attachExamToWeek(3,'e1'),'Faculty can attach an existing subject exam to a week');
ok(r.read('subjectWorkspaceContent').some(item=>item.week===3&&item.type==='exam'&&item.examId==='e1'),'weekly content stores an exam reference without moving the exam');
ok(!!r.d.querySelector('.week-stack .attached-exam-link'),'attached exam appears inside the selected week');
ok(!!r.d.querySelector('.faculty-exam-cell'),'the original exam cell remains in the Examinations section');

r.w.FacultySubjectWorkspace.showTab('members');
ok(/Prof\.|F1/.test(r.d.querySelector('.workspace-main').textContent),'Members lists faculty across the subject');
ok(!!r.d.querySelector('.workspace-table table')&&!!r.d.querySelector('.member-row'),'Members use a professor table');
r.d.querySelector('.member-row').click();
ok(!!r.d.querySelector('.member-section-table'),'Professor row expands to a handled-sections table');
r.w.FacultySubjectWorkspace.showTab('grades');
ok(!!r.d.querySelector('.workspace-grade-table table'),'Grades provides a section assessment table');
r.w.FacultySubjectWorkspace.showTab('logs');
ok([...r.d.querySelectorAll('.workspace-subtabs button')].some(button=>button.textContent.includes('Faculty')),'Logs provides a Faculty subtab');
ok([...r.d.querySelectorAll('.workspace-subtabs button')].some(button=>button.textContent.includes('Students')),'Logs provides a Students subtab');
r.w.FacultySubjectWorkspace.showTab('main');
const courseExamQuestionButton=r.d.querySelector('.faculty-exam-cell-actions button[aria-label="Open questions"]');
ok(!!courseExamQuestionButton,'Faculty Course Page exam cells provide a direct Questions icon');
courseExamQuestionButton.click();
ok(/Question bank/.test(r.d.getElementById('examsView').textContent),'Faculty Course Page Questions icon opens the selected exam question bank');
r.w.displayAllFacultyExams();
const listQuestionButton=r.d.querySelector('#examsView .exam-item-actions > .questions');
ok(!!listQuestionButton,'Faculty exam lists expose Questions beside the settings menu');
listQuestionButton.click();
ok(/Question bank/.test(r.d.getElementById('examsView').textContent),'Faculty exam-list Questions icon opens the selected exam question bank');
seed.subjectWorkspaceContent=r.read('subjectWorkspaceContent');
r.w.close();

let student=load('student.html',{...seed,currentUser:{username:'S1',role:'student'}});
student.w.openStudentSubject('SUB1');
ok(/Week 3/.test(student.d.getElementById('studentSubjectDetail').textContent),'Faculty weekly content appears on the real Student subject page');
ok(/Interaction Design/.test(student.d.getElementById('studentSubjectDetail').textContent),'Student sees the published content cell');
ok(student.d.querySelector('.learning-cell.always-open')?.open,'Student content is flat inside its week unless faculty enables collapsing');
const attachedExam=student.d.querySelector('#studentSubjectDetail .attached-exam-link');
ok(!!attachedExam,'Student sees the exam attached to the week');
attachedExam?.click();
ok(student.d.getElementById('takeExamModal').classList.contains('active'),'attached weekly exam opens the normal examination details prompt');
student.w.close();
process.exit(0);
