'use strict';
const assert = require('assert');
const { prepare, TARGET } = require('../server/lifecycle-demo');
const sections = Array.from({ length: 60 }, (_, index) => ({ id: `SEC-${index + 1}`, yearLevel: index % 4 + 1, capacity: 50 }));
const students = sections.flatMap(section => Array.from({ length: 20 }, (_, index) => ({ id: `${section.id}-ST-${index}`, sections: [section.id] })));
const records = { users: [{ username: 'admin', role: 'admin' }, ...students.map(student => ({ username: student.id, role: 'student' }))], students, faculty: [], coordinators: [], sections, sectionSubjects: sections.map(section => ({ sectionId: section.id, assignments: [{ id: `OFR-${section.id}`, subjectCode: 'CICS101' }] })), studentEnrollments: [], systemSettings: { currentAcademicPeriodId: 'AY-2026-2027-FIRST-SEMESTER' } };
const store = { read: (key, fallback) => records[key] ?? fallback };
const result = prepare(store);
assert.strictEqual(result.added, TARGET);
assert.strictEqual(result.summary.students, 3140);
assert.strictEqual(result.summary.professors, 280);
assert.strictEqual(result.summary.coordinators, 28);
assert.strictEqual(result.summary.deans, 5);
assert.strictEqual(result.summary.firstSemesterEnrollments, 1600);
assert.strictEqual(new Set(result.records.users.map(user => user.username)).size, result.records.users.length);
assert.ok(result.records.users.every(user => user.lifecycleHistory?.length));
assert.ok(result.records.users.filter(user => user.lifecycleDemoSeed === 'v1').some(user => user.status === 'graduated'));
assert.ok(result.records.users.filter(user => user.lifecycleDemoSeed === 'v1').some(user => user.status === 'transferred'));
assert.ok(sections.every(section => result.records.students.filter(student => student.sections.includes(section.id)).length <= section.capacity));
assert.ok(result.records.studentEnrollments.every(item => item.academicPeriodId === 'AY-2026-2027-FIRST-SEMESTER'));
const seeded = { read: (key, fallback) => result.records[key] ?? records[key] ?? fallback };
assert.strictEqual(prepare(seeded).alreadyApplied, true);
console.log('Lifecycle demo: 3,453 accounts, history, section capacity, current-term enrollments, and idempotence passed.');
