const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
const today=new Date().toLocaleDateString('en-CA');

console.log('=== QUESTION MEDIA. Validation, persistence, preview, and fallback ===');
let s=SEED();
let r=load('faculty.html',{...s,currentUser:{username:'F1',role:'faculty'}});
r.w.manageQuestions('e1');
r.w.openQuestionModal();
r.d.getElementById('questionText').value='Identify the diagram';
const options=[...r.d.querySelectorAll('#optionsContainer .option-input-group')];
options[0].querySelector('input[type="text"]').value='A';
options[1].querySelector('input[type="text"]').value='B';
options[0].querySelector('input[type="radio"]').checked=true;
r.d.getElementById('questionImageUrl').value='javascript:alert(1)';
r.d.getElementById('questionImageAlt').value='A labelled diagram';
r.w.saveQuestion();
ok(!r.read('questions').some(q=>q.text==='Identify the diagram'),'unsafe image scheme is rejected');
r.d.getElementById('questionImageUrl').value='https://example.com/diagram.png';
r.d.getElementById('questionImageAlt').value='';
r.w.saveQuestion();
ok(!r.read('questions').some(q=>q.text==='Identify the diagram'),'image without alternative text is rejected');
r.d.getElementById('questionImageAlt').value='A labelled diagram';
r.d.getElementById('questionImageCaption').value='Figure 1';
r.d.getElementById('questionLinkUrl').value='https://example.com/reference';
r.d.getElementById('questionLinkText').value='Read the reference';
r.w.renderQuestionInlinePreview();
ok(!!r.d.querySelector('#questionInlinePreview img'),'valid image appears in live authoring preview');
ok(/Read the reference/.test(r.d.getElementById('questionInlinePreview').textContent),'descriptive link appears in preview');
r.w.saveQuestion();
const saved=r.read('questions').find(q=>q.text==='Identify the diagram');
ok(saved.imageAlt==='A labelled diagram' && saved.linkText==='Read the reference','media metadata persists with question');
r.w.close();

s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
s.questions[0]={...s.questions[0],imageUrl:'https://example.com/diagram.png',imageAlt:'A labelled diagram',
  imageCaption:'Figure 1',linkUrl:'https://example.com/reference',linkText:'Read the reference'};
r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
const image=r.d.querySelector('#examQuestionsContainer .question-media img');
ok(!!image && image.alt==='A labelled diagram','student receives accessible question image');
ok(r.d.querySelector('.question-resource a').getAttribute('rel').includes('noopener'),'external resource is opened safely');
image.dispatchEvent(new r.w.Event('error'));
ok(image.hidden,'broken image is hidden');
ok(!r.d.querySelector('.question-media-error').hidden,'broken image shows readable fallback');
ok(/Q1/.test(r.d.querySelector('.q-title').textContent),'written prompt remains when image fails');
r.w.close();
process.exit(0);
