'use strict';
const assert = require('assert');
const { validateAudit, validateApprovals, validateProtectedWrite } = require('../server/protected-write');
const coordinator = { username: 'coord.001', role: 'coordinator' };
const dean = { username: 'dean.demo', role: 'dean' };
const admin = { username: 'admin', role: 'admin' };
const log = [{ id: 'a1', actorId: 'coord.001', actorRole: 'coordinator' }];
assert.doesNotThrow(() => validateAudit(log, [...log, { id: 'a2', actorId: 'coord.001', actorRole: 'coordinator' }], coordinator));
assert.throws(() => validateAudit(log, [], coordinator), /append-only/i);
assert.throws(() => validateAudit(log, [{ ...log[0], actorId: 'someone' }], coordinator), /changed or removed/i);
const pending = { id:'APR-1', type:'professor-assignment', requesterId:'coord.001', requesterRole:'coordinator', targetType:'subject-offering', targetId:'OFR-1', proposedChange:{facultyId:'F2'}, reason:'Coverage required.', academicPeriod:'2026-1', submittedAt:'2026-09-21T08:00:00Z', status:'pending', reviewerId:'', reviewerRole:'dean', reviewerRemarks:'', decisionAt:'', history:[{status:'pending',at:'2026-09-21T08:00:00Z',actorId:'coord.001',actorRole:'coordinator',remarks:'Coverage required.'}] };
assert.doesNotThrow(() => validateApprovals([], [pending], coordinator));
assert.throws(() => validateApprovals([], [{ ...pending, requesterId:'other' }], coordinator), /owned pending/i);
const decided={...pending,status:'approved',reviewerId:'dean.demo',reviewerRole:'dean',reviewerRemarks:'Verified.',decisionAt:'2026-09-21T09:00:00Z',history:[...pending.history,{status:'approved',at:'2026-09-21T09:00:00Z',actorId:'dean.demo',actorRole:'dean',remarks:'Verified.'}]};
assert.doesNotThrow(() => validateApprovals([pending], [decided], dean));
assert.throws(() => validateApprovals([pending], [{ ...decided, proposedChange:{facultyId:'F9'} }], dean), /cannot alter/i);
assert.throws(() => validateApprovals([pending], [{ ...decided, reviewerId:'other' }], dean), /limited/i);
assert.throws(() => validateProtectedWrite({read:()=>[]}, admin, 'academicPeriods', []), /protected academic-period workflow/i);
const cancelled={...pending,status:'cancelled',history:[...pending.history,{status:'cancelled',at:'2026-09-21T09:00:00Z',actorId:'admin',actorRole:'admin',remarks:'Obsolete request.'}]};
assert.doesNotThrow(() => validateApprovals([pending], [cancelled], admin));
assert.throws(() => validateApprovals([pending], [{...cancelled,proposedChange:{facultyId:'F9'}}], admin), /cannot decide or alter/i);
console.log('✅ approval transitions are role-bound and audit history is append-only');
