const {load,SEED}=require('./harness');
const fs=require('fs'),path=require('path');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
const today=new Date().toLocaleDateString('en-CA');

(async()=>{
console.log('=== QUESTION REPORTS. Student report to scoped Faculty resolution ===');
const sharedCss=fs.readFileSync(path.join(__dirname,'..','css','shared-ui.css'),'utf8');
const reportCss=fs.readFileSync(path.join(__dirname,'..','css','report-status.css'),'utf8');
ok(/--status-pending:\s*#EDC27B/.test(sharedCss)&&/#reportsView \.question-report\.pending,[\s\S]*border-color: var\(--status-pending\) !important/.test(reportCss),'Reports page binds its dark-mode Pending border directly to the shared orange token');
ok(!/#[0-9a-f]{3,8}\b/i.test(reportCss),'report component contains no hard-coded colors');
let s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
let r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
ok(!!r.d.querySelector('.report-question-btn'),'each rendered question offers Report question');
ok(!!r.d.querySelector('.q-head .report-question-btn'),'report action is kept in the question toolbar');
ok(/Report/.test(r.d.querySelector('.report-question-btn').textContent)&&/var\(--danger\)/.test(sharedCss),'report control has a visible name and shared semantic red color');
r.w.openQuestionReport('q1');
ok(r.d.getElementById('questionReportModal').classList.contains('active'),'report dialog opens for selected question');
r.d.getElementById('questionReportCategory').value='wrong-answer';
r.d.getElementById('questionReportDetails').value='Both choices appear valid.';
ok(r.w.submitQuestionReport()===true,'complete report is accepted');
const report=r.read('questionReports')[0];
ok(report.studentId==='S1' && report.questionId==='q1' && report.status==='open','report stores actor, target, and open status');
r.w.openQuestionReport('q1');
r.d.getElementById('questionReportDetails').value='Duplicate report';
ok(r.w.submitQuestionReport()===false,'duplicate open report is rejected');
r.w.close();

s.questionReports=[report,{id:'other',studentId:'S2',examId:'foreign',questionId:'qx',category:'other',details:'Hidden',status:'open'}];
r=load('faculty.html',{...s,currentUser:{username:'F1',role:'faculty'}});
ok(r.d.querySelector('#sidebar [data-panel="reports-tab"] .nav-count')?.textContent==='1','Faculty sidebar shows the owned pending-report count');
ok(/Both choices appear valid/.test(r.d.querySelector('.header-inbox-panel')?.textContent||''),'Faculty header inbox includes owned question reports');
r.w.displayQuestionReports();
const view=r.d.getElementById('reportsView');
ok(/Both choices appear valid/.test(view.textContent),'Faculty sees report for an owned exam');
ok(!/Hidden/.test(view.textContent),'Faculty cannot see reports for unowned exams');
const reportTabs=[...view.querySelectorAll('.report-filter-tab')];
ok(reportTabs.length===4&&reportTabs.map(tab=>tab.textContent.replace(/\d+/g,'').trim()).join('|')==='All|Pending|Resolved|Dismissed','reports use the four status tabs');
ok(!view.querySelector('#reportStatusFilter')&&!/\d+ open/.test(view.querySelector('.exams-header')?.textContent||''),'old open count and status dropdown are removed');
ok(reportTabs.every(tab=>tab.querySelector('.report-filter-count')),'every status tab includes its count pill');
ok(view.querySelector('.question-report').classList.contains('pending')&&view.querySelector('.report-status').textContent==='Pending','open and in-review reports share the Pending card status');
const sortOptions=[...view.querySelectorAll('#reportSort option')].map(option=>option.textContent);
ok(['Recent','Reporter name','Subject','Section','Status'].every(label=>sortOptions.includes(label)),'report sorting includes recent, reporter, subject, section, and status');
const directionBefore=view.querySelector('.report-sort-direction').className;r.w.toggleReportSort();
ok(r.d.querySelector('.report-sort-direction').className!==directionBefore,'ascending and descending control transforms when toggled');
const reportActions=[...view.querySelectorAll('.question-report .report-action-icon')];
ok(reportActions.length===4&&!/Notify student|Reopen/.test(view.textContent),'report row keeps only review, resolve, dismiss, and settings icons');
ok(/S1/.test(view.querySelector('.report-card-head')?.textContent||'')&&!!view.querySelector('.report-problem-pill'),'report header identifies the reporter and the problem is a pill');
ok(!!view.querySelector('.report-profile-link')&&view.querySelectorAll('.report-subject-link').length===2,'reporter name and subject code/name are links');
view.querySelector('.report-profile-link').click();
ok(r.d.getElementById('roleProfileOverlay')?.classList.contains('open'),'reporter name opens the student profile');r.w.RoleProfileViewer.close();
view.querySelector('.report-subject-link').click();
ok(r.d.getElementById('subject-workspace-tab').style.display!=='none','subject link opens the subject Course Page');r.w.switchTab('reports-tab');
view.querySelector('.report-action-icon.settings').click();
ok(/View student profile/.test(view.querySelector('.report-settings-menu.open')?.textContent||'')&&/Mail student/.test(view.querySelector('.report-settings-menu.open')?.textContent||'')&&/View question/.test(view.querySelector('.report-settings-menu.open')?.textContent||'')&&/Block from reporting/.test(view.querySelector('.report-settings-menu.open')?.textContent||'')&&/Copy ID/.test(view.querySelector('.report-settings-menu.open')?.textContent||''),'settings menu contains the five reporter actions');
ok(r.w.viewReportStudent(report.id)===true&&r.d.getElementById('roleProfileOverlay')?.classList.contains('open'),'settings opens the reporter profile');r.w.RoleProfileViewer.close();
let mailing=r.w.mailReportStudent(report.id);r.d.querySelector('.confirm-box textarea').value='I am reviewing your question report.';r.d.querySelector('.confirm-box .confirm-ok').click();
ok(await mailing&&r.read('studentNotifications').some(item=>item.type==='faculty-mail'&&item.studentId==='S1'),'settings mail action sends a private student message');
ok(r.w.openReportedQuestion(report.id)===true&&r.d.getElementById('questionModal').classList.contains('active'),'clicking a report opens its question editor');
ok(/Both choices appear valid/.test(r.d.getElementById('reportedQuestionContext').textContent),'question editor shows the report context beside editable settings');
ok(r.d.getElementById('reportedQuestionContext').classList.contains('pending')&&/S1/.test(r.d.getElementById('reportedQuestionContext').textContent),'embedded report matches the status card and reporter context');
ok(/#reportedQuestionContext > \.report-main > \.report-card-head > \.report-status[\s\S]*position: absolute !important;[\s\S]*top: 14px !important;[\s\S]*right: 14px !important/.test(reportCss),'embedded report status pill is anchored to the card top-right corner');
ok(r.d.querySelectorAll('#reportedQuestionContext .report-action-icon').length===4&&!r.d.querySelector('#reportedQuestionContext textarea'),'embedded report uses the same four icon actions and keeps resolution notes in the prompt');
r.w.closeQuestionModal();
ok(r.d.getElementById('reports-tab').style.display!=='none'&&/Both choices appear valid/.test(r.d.getElementById('reportsView').textContent),'question editor Back returns to the originating reports page');
let resolving=r.w.requestReportStatus(report.id,'resolved');
const resolutionDialog=r.d.querySelector('.confirm-box textarea');resolutionDialog.value='Confirmed the answer key issue.';r.d.querySelector('.confirm-box .confirm-ok').click();
ok(await resolving,'Faculty can resolve an owned report after adding a note');
ok(r.read('questionReports').find(item=>item.id===report.id).status==='resolved','resolved status persists');
ok(r.w.toggleQuestionReport(report.id,'open')===true,'resolved report can be reopened');
ok(r.w.toggleQuestionReport(report.id,'reviewed')===true,'report can be marked reviewed');
r.w.selectReportTab('pending');
ok(!!r.d.querySelector('.question-report')&&r.d.querySelector('.report-filter-tab.active')?.textContent.includes('Pending'),'pending tab combines open and in-review reports');
let skipping=r.w.requestReportStatus(report.id,'dismissed');
ok(!!r.d.querySelector('.resolution-dialog .dialog-close-x')&&!!r.d.querySelector('.resolution-dialog .confirm-skip'),'resolution prompt uses a top-right close icon and Skip action');
r.d.querySelector('.resolution-dialog .confirm-skip').click();
ok(await skipping&&r.read('questionReports').find(item=>item.id===report.id).status==='dismissed','report can be dismissed while skipping the optional note');
r.w.toggleQuestionReport(report.id,'open');
r.w.openReportedQuestion(report.id);
r.w.saveQuestionReportNote(report.id,'The answer key was corrected.');
ok(r.read('questionReports').find(item=>item.id===report.id).resolutionNote==='The answer key was corrected.','resolution note is retained by the prompt workflow');
let notifying=r.w.notifyReportResolution(report.id);
r.d.getElementById('confirmYes').click();
ok(await notifying,'confirmed notification is created');
const notice=r.read('studentNotifications').find(item=>/was corrected/.test(item.message));
ok(notice.studentId==='S1' && /answer key/.test(notice.message),'notification is scoped to reporter and contains note');
let blocking=r.w.blockReportStudent(report.id);r.d.getElementById('confirmYes').click();
ok(await blocking,'Faculty can block the reporter from submitting new reports');
ok(r.w.createQuestionReport({studentId:'S1',examId:'e1',questionId:'q2',category:'other',details:'A new concern'}).reason==='blocked','blocked reporter cannot submit another report to that Faculty');
r.w.close();

r=load('student.html',{...s,studentNotifications:[notice],currentUser:{username:'S1',role:'student'}});
ok(r.d.getElementById('studentNotificationsCard').style.display==='block','Student sees report-update card');
ok(/answer key was corrected/.test(r.d.getElementById('studentNotifications').textContent),'Student sees Faculty resolution message');
ok(/answer key was corrected/.test(r.d.querySelector('.header-inbox-panel')?.textContent||''),'Student header inbox includes the private report update');
r.w.close();
process.exit(0);
})();
