const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== RELATIONSHIPS. Irregular Students and section-subject offerings ===');
const seed=SEED(); seed.students[0].sections=['A','B']; seed.sections=[{id:'A',name:'A'},{id:'B',name:'B'}];
let r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
ok(r.read('students')[0].sections.length===2,'multiple section memberships are preserved for irregular students');
r.w.editItem('students',0);
const sectionChoices=[...r.d.querySelectorAll('#sSections input[type="checkbox"]')];
ok(sectionChoices.length===2&&sectionChoices.every(input=>input.name==='studentSection'),'Student editor exposes section checkbox cards for irregular enrolment');
sectionChoices.forEach(input=>input.checked=true);
r.d.getElementById('sID').value='S1'; r.d.getElementById('sLast').value='Cruz'; r.d.getElementById('sFirst').value='Juan';
r.w.saveItem('students');
ok(r.read('students')[0].sections.length===2,'selecting cards saves multiple sections');
ok(r.d.querySelectorAll('.upload-action').length===4,'native file controls are replaced by four upload icon actions');
ok([...r.d.querySelectorAll('.upload-action')].every(label=>label.getAttribute('aria-label')&&label.title),'upload icons keep labels and tooltips');
ok(r.d.querySelectorAll('.management-table-shell > .action-box').length===5,'other management actions use the same table-corner pattern');
ok(r.d.querySelectorAll('.management-page-head').length===5,'management pages and the unassigned-professor table show titles and descriptions');
ok(r.d.querySelectorAll('.export-action').length===7,'Admin tables provide CSV export icons');
const adminCss=require('fs').readFileSync(require('path').join(__dirname,'..','css','admin-modern.css'),'utf8');
ok(/\.action-box \{[^}]*top:0/.test(adminCss)&&/\.management-table-shell \{[^}]*padding-top:52px/.test(adminCss),'page actions occupy a separate top-right row above the table');
r.w.close();

const sectionSeed=SEED(); sectionSeed.allotments=[]; sectionSeed.sections=[{id:'A',name:'A'},{id:'B',name:'B'}];
sectionSeed.students=[{id:'S1',last:'Cruz',first:'Juan',sections:['A']},{id:'S2',last:'Reyes',first:'Ana',sections:['B']}];
sectionSeed.sectionSubjects=[{sectionId:'A',subjectCodes:['SUB1']},{sectionId:'B',subjectCodes:['SUB1']}];
sectionSeed.subjectAssignments=[{subjectCode:'SUB1',facultyIds:['F1']}];
r=load('faculty.html',{...sectionSeed,currentUser:{username:'F1',role:'faculty'}});
r.w.switchTab('students-tab',r.d.querySelectorAll('.tab-btn')[2]);
const rosterTabs=[...r.d.querySelectorAll('.student-section-tab')];
const rosterText=rosterTabs.map(tab=>{tab.click();return r.d.getElementById('studentsView').textContent}).join(' ');
ok(rosterTabs.length===2&&/S1/.test(rosterText)&&/S2/.test(rosterText),'one professor sees students in separate tabs for multiple handled sections');
r.w.close();

const addedSeed=SEED();
addedSeed.sections=addedSeed.sections||[];addedSeed.sectionSubjects=addedSeed.sectionSubjects||[];addedSeed.studentEnrollments=addedSeed.studentEnrollments||[];
addedSeed.faculty.push({id:'F-NEW',last:'Rivera',first:'Nora'});
addedSeed.users.push({username:'F-NEW',password:'rivera2',role:'faculty'});
addedSeed.subjects.push({code:'NEW101',name:'Newly Assigned Subject'});
addedSeed.sections.push({id:'NEW-SECTION',name:'New Section'});
addedSeed.sectionSubjects.push({sectionId:'NEW-SECTION',assignments:[{id:'OFR-NEW',subjectCode:'NEW101',facultyId:'F-NEW'}]});
addedSeed.subjectAssignments.push({subjectCode:'NEW101',facultyIds:['F-NEW']});
addedSeed.students.push({id:'S-NEW',last:'Added',first:'Student',sections:['NEW-SECTION']});
addedSeed.studentEnrollments=(addedSeed.studentEnrollments||[]).concat({id:'ENR-NEW',studentId:'S-NEW',offeringId:'OFR-NEW',subjectCode:'NEW101',sectionId:'NEW-SECTION'});
r=load('faculty.html',{...addedSeed,currentUser:{username:'F-NEW',role:'faculty'}});
r.w.switchTab('students-tab');
ok(/NEW-SECTION/.test(r.d.querySelector('.student-section-tabs').textContent)&&/S-NEW/.test(r.d.querySelector('.student-roster-table').textContent)&&/NEW101/.test(r.d.querySelector('.student-roster-table').textContent),'new faculty and student section assignments appear in the faculty roster');
const refreshedStudents=JSON.parse(r.w.localStorage.getItem('students'));refreshedStudents.push({id:'S-LATE',last:'Live',first:'Update',sections:['NEW-SECTION']});r.w.localStorage.setItem('students',JSON.stringify(refreshedStudents));
r.w.displayMyStudents();
ok(/S-LATE/.test(r.d.querySelector('.student-roster-table').textContent),'faculty roster rereads saved section membership instead of showing stale student data');
r.w.close(); process.exit(0);
