const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== RELATIONSHIPS. Per-subject sections and current management flows ===');

const seed=SEED();
seed.sections=[{id:'A',name:'1',capacity:30},{id:'B',name:'2',capacity:30}];
seed.students[0].sections=['A','B'];
seed.studentEnrollments=[{id:'EA',studentId:'S1',subjectCode:'SUB1',sectionId:'A'},{id:'EB',studentId:'S1',subjectCode:'SUB2',sectionId:'B'}];
let r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
ok(r.read('studentEnrollments').map(item=>item.sectionId).sort().join(',')==='A,B','one student can use different sections for different subjects');
r.w.editItem('students',0);
ok(!r.d.getElementById('sSections')&&r.d.getElementById('sYear'),'Student editor uses year level instead of a global section picker');
r.d.getElementById('sLast').value='Cruz';r.d.getElementById('sFirst').value='Juan';r.w.saveItem('students');
ok(r.read('studentEnrollments').length===2,'editing identity details preserves per-subject section enrollments');
ok(r.d.querySelectorAll('.upload-action').length===3,'current CSV imports use three accessible upload actions');
ok([...r.d.querySelectorAll('.upload-action')].every(label=>label.getAttribute('aria-label')&&label.title),'upload icons keep labels and tooltips');
ok(r.d.querySelectorAll('.management-table-shell > .action-box').length===4,'management actions use the current table-corner pattern');
ok(r.d.querySelectorAll('.management-page-head').length===5,'management pages retain titles and descriptions');
ok(r.d.querySelectorAll('.export-action').length===6,'all six Admin data tables provide CSV export actions');
r.w.close();

const facultySeed=SEED();
facultySeed.sections=[{id:'A',name:'1',capacity:30},{id:'B',name:'2',capacity:30}];
facultySeed.students=[{id:'S1',last:'Cruz',first:'Juan'},{id:'S2',last:'Reyes',first:'Ana'}];
facultySeed.sectionSubjects=[{sectionId:'A',assignments:[{id:'OA',subjectCode:'SUB1',facultyId:'F1'}]},{sectionId:'B',assignments:[{id:'OB',subjectCode:'SUB1',facultyId:'F1'}]}];
facultySeed.studentEnrollments=[{id:'E1',studentId:'S1',subjectCode:'SUB1',sectionId:'A'},{id:'E2',studentId:'S2',subjectCode:'SUB1',sectionId:'B'}];
r=load('faculty.html',{...facultySeed,currentUser:{username:'F1',role:'faculty'}});
r.w.switchTab('students-tab',r.d.querySelectorAll('.tab-btn')[2]);
let tabs=[...r.d.querySelectorAll('.student-section-tabs[aria-label^="Sections"] .student-section-tab')];
const rosterText=tabs.map(tab=>{tab.click();return r.d.querySelector('.student-roster-table').textContent}).join(' ');
ok(tabs.length===2&&/S1/.test(rosterText)&&/S2/.test(rosterText),'faculty roster separates students by handled subject section');
const refreshed=r.read('students');refreshed.push({id:'S3',last:'Live',first:'Update'});r.w.localStorage.setItem('students',JSON.stringify(refreshed));
const enrollments=r.read('studentEnrollments');enrollments.push({id:'E3',studentId:'S3',subjectCode:'SUB1',sectionId:'A'});r.w.localStorage.setItem('studentEnrollments',JSON.stringify(enrollments));
r.w.displayMyStudents();r.w.selectStudentRosterSection('A');
ok(/S3/.test(r.d.querySelector('.student-roster-table').textContent),'faculty roster rereads newly saved student enrollment data');
r.w.close();process.exit(0);
