const {load}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== CURRICULUM SAMPLE DATA. Programs, years, offerings, and IDs ===');
const r=load('login.html',{users:[],faculty:[],students:[],subjects:[],subjectAssignments:[],allotments:[],exams:[],questions:[]},{query:'?role=admin'});
const faculty=r.read('faculty'),students=r.read('students'),subjects=r.read('subjects'),sections=r.read('sections'),records=r.read('sectionSubjects'),enrollments=r.read('studentEnrollments');
const offers=records.flatMap(record=>record.assignments.map(item=>({...item,sectionId:record.sectionId})));
ok(faculty.length===28&&new Set(faculty.map(item=>item.id)).size===28&&faculty.every(item=>/^\d{2}-\d{5}-\d{3}$/.test(item.id)),'28 teachers use unique NN-NNNNN-NNN IDs');
ok(subjects.length===24&&sections.length===15&&students.length===619,'three programs, 15 sections, and 619 students are seeded');
ok(students.every(item=>/^\d{4}-\d{5}$/.test(item.id)),'students use YYYY-NNNNN IDs');
ok(subjects.every(item=>/^(CCS|CIT|CIS)\d{3}-\d{2}$/.test(item.code)),'subjects use program-prefixed codes');
ok(new Set(offers.map(item=>item.id)).size===offers.length,'every section-subject offering has a unique ID');
ok(students.every(student=>{const count=enrollments.filter(item=>item.studentId===student.id).length;return student.id==='2025-00002'?count===6:count>=2&&count<=3;}),'sample students have two or three offerings, while Maria has six demo subjects');
ok(faculty.filter(person=>!offers.some(item=>item.facultyId===person.id)).length===5,'demo data includes five unassigned professors after expanding Maria Reyes’s teaching load');
const hci=offers.filter(item=>item.subjectCode==='CCS212-24');
ok(new Set(hci.map(item=>item.facultyId)).size>1&&new Set(hci.map(item=>item.sectionId)).size>1,'the same subject has different teachers across sections');
ok(students.some(student=>new Set(enrollments.filter(item=>item.studentId===student.id).map(item=>item.sectionId)).size>1),'sample data includes irregular students');
ok(new Set(students.flatMap(item=>item.sections.map(section=>section.charAt(0)))).size===4,'students span all four year levels');
ok(sections.every(section=>/^\d(?:BSCS|BSIT|BSIS)-\d+$/.test(section.id)),'section IDs use year-curriculum-number with no trailing letters');
r.w.close();
const old={users:[{username:'admin',password:'admin123',role:'admin'}],faculty:[{id:'12-34567-890',last:'Reyes',first:'Maria'}],students:[{id:'2024-00001',last:'Dela Cruz',first:'Juan',sections:['BSCS-3A']}],subjects:[],demoCurriculumVersion:5,currentUser:{username:'admin',role:'admin'}};
const direct=load('admin.html',old);
ok(direct.read('students').length===619&&direct.d.getElementById('countStudents').textContent==='619','direct Admin refresh migrates and renders the latest demo data');
ok(direct.d.querySelectorAll('#unassignedFacultyTable tr').length===6,'Admin lists the five professors without assigned subjects');
const demoUsers=direct.read('users'),demoAudit=direct.read('applicationAuditLog'),demoSubs=direct.read('studentSubmissions');
const demoExams=direct.read('exams'),demoQuestions=direct.read('questions'),demoEnrollments=direct.read('studentEnrollments');
const demoReports=direct.read('questionReports'),demoAnnouncements=direct.read('adminAnnouncements');
ok(['open','reviewed','resolved','dismissed'].every(status=>demoReports.some(report=>report.status===status)),'demo question reports cover open, reviewed, resolved, and dismissed statuses');
ok(['open','reviewed','resolved','dismissed'].every(status=>demoReports.filter(report=>report.status===status).length===3),'demo queue provides three examples under every report-status filter');
ok(demoAnnouncements.length>=2&&/Scheduled maintenance/.test(direct.d.querySelector('.header-inbox-panel')?.textContent||''),'Admin announcements are seeded and appear in the header inbox');
ok(demoUsers.find(user=>user.username==='2025-00002').password==='santos2025'&&demoUsers.find(user=>user.username==='23-32534-345').password==='reyes23','named Student and Faculty demo credentials are fixed');
const reyesOfferings=records.flatMap(record=>(record.assignments||[]).map(item=>({...item,sectionId:record.sectionId}))).filter(item=>item.facultyId==='23-32534-345');
const santosCodes=new Set(demoEnrollments.filter(item=>item.studentId==='2025-00002').map(item=>item.subjectCode));
ok(new Set(reyesOfferings.map(item=>item.subjectCode)).size>=5&&new Set(reyesOfferings.map(item=>item.sectionId)).size>=5,'Maria Reyes handles several subjects across several sections');
ok(new Set(reyesOfferings.filter(item=>santosCodes.has(item.subjectCode)).map(item=>item.subjectCode)).size>=4,'Maria Reyes teaches several subjects enrolled by Maria Santos');
const mariaSubs=demoSubs.filter(item=>item.studentId==='2025-00002');
ok(mariaSubs.length===2&&mariaSubs.every(item=>item.answers.length>=5&&item.answers.every(answer=>answer.questionId))&&demoAudit.filter(item=>item.actorId==='2025-00002').length>=3,'demo student retains two complete expired exam histories and activity logs');
ok(demoAudit.filter(item=>item.actorId==='23-32534-345').length>=5,'demo faculty has login, exam, publish, and grading activity');
ok(subjects.every(subject=>{const count=demoExams.filter(exam=>exam.subjectCode===subject.code).length;return count>=1&&count<=3;}),'every subject has one to three assessments');
const timedExams=demoExams.filter(exam=>exam.durationMinutes>0);
ok(timedExams.every(exam=>exam.durationMinutes>=30&&exam.durationMinutes<=120)&&new Set(timedExams.map(exam=>exam.durationMinutes)).size===6,'timed assessment durations vary from 30 minutes to two hours');
const scheduledExams=demoExams.filter(exam=>exam.date);
const pastScheduled=scheduledExams.filter(exam=>exam.date<='2026-08-31'),movedToNextWeek=scheduledExams.filter(exam=>exam.date>='2026-09-07'&&exam.date<='2026-09-13');
ok(pastScheduled.length===4&&movedToNextWeek.length>0&&scheduledExams.every(exam=>exam.date>='2026-08-18'&&exam.date<='2026-09-24'),'old schedules move to next week while four deliberate past examples remain');
ok(demoExams.every(exam=>{const count=demoQuestions.filter(question=>question.examId===exam.id).length;return count>=5&&count<=20;}),'every assessment contains five to twenty short items');
ok(new Set(demoQuestions.map(question=>question.type)).size===6,'questions cover choice, true/false, number, fill-blank, matching, and essay formats');
const mistakesDemo=demoExams.find(exam=>exam.id==='DEMO-REVIEW-MISTAKES');
ok(mistakesDemo&&mistakesDemo.date>='2026-09-07'&&mistakesDemo.date<='2026-09-13','the previous review demo is rescheduled into next week');
const liveDemo=demoExams.find(exam=>exam.title.includes('Live Demo Quiz'));
ok(liveDemo&&liveDemo.date==='2026-08-25'&&liveDemo.start==='00:00'&&liveDemo.end==='23:59'&&liveDemo.durationMinutes===30&&liveDemo.sections.includes('2BSCS-1'),'named Student retains one of the deliberately missed all-day assessments');
const alwaysOpen=demoExams.find(exam=>exam.id==='DEMO-ALWAYS-OPEN');
ok(alwaysOpen&&alwaysOpen.maxAttempts===99&&!alwaysOpen.date&&!alwaysOpen.end&&demoQuestions.filter(question=>question.examId===alwaysOpen.id).length===10,'Student has a 99-attempt practice exam with no deadline');
const mariaRelevant=demoExams.filter(exam=>santosCodes.has(exam.subjectCode)),mariaMissed=mariaRelevant.filter(exam=>exam.date&&exam.date<='2026-08-31'&&!mariaSubs.some(submission=>submission.examId===exam.id));
ok(mariaMissed.length===2,'named Student retains exactly two missed assessments');
direct.w.close();
const staleStudentData={users:demoUsers,faculty,students,subjects,sections,sectionSubjects:records,studentEnrollments:demoEnrollments.filter(item=>item.studentId!=='2025-00002'||['CCS211-24','CCS212-24'].includes(item.subjectCode)),subjectAssignments:direct.read('subjectAssignments'),exams:demoExams,questions:demoQuestions,studentSubmissions:demoSubs.filter(item=>item.studentId!=='2025-00002').concat(demoSubs.filter(item=>item.studentId==='2025-00002').slice(0,2)),applicationAuditLog:demoAudit,demoCurriculumVersion:12,currentUser:{username:'2025-00002',role:'student'}};
const refreshedStudent=load('student.html',staleStudentData);
ok(refreshedStudent.d.getElementById('statSubjects').textContent==='6','direct Student refresh installs the latest six-subject Maria demo data');
ok(refreshedStudent.d.getElementById('statCompleted').textContent==='2','direct Student refresh restores Maria’s two completed expired exams');
refreshedStudent.w.close();
const studentLogin=load('login.html',{users:[],faculty:[],students:[],subjects:[]},{query:'?role=student'});
ok(studentLogin.d.getElementById('username').value==='2025-00002'&&studentLogin.d.getElementById('password').value==='santos2025','Student login prefills the named demo account');studentLogin.w.close();
const facultyLogin=load('login.html',{users:[],faculty:[],students:[],subjects:[]},{query:'?role=faculty'});
ok(facultyLogin.d.getElementById('username').value==='23-32534-345'&&facultyLogin.d.getElementById('password').value==='reyes23','Faculty login prefills the named demo account');facultyLogin.w.close();
process.exit(0);
