const {load}=require('./harness');
const officialCurricula=require('../assets/philippine-curricula.json');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== CURRICULUM SAMPLE DATA. Programs, years, offerings, and IDs ===');
const r=load('login.html',{users:[],faculty:[],students:[],subjects:[],subjectAssignments:[],allotments:[],exams:[],questions:[],curricula:officialCurricula},{query:'?role=admin'});
const faculty=r.read('faculty'),students=r.read('students'),subjects=r.read('subjects'),sections=r.read('sections'),records=r.read('sectionSubjects'),enrollments=r.read('studentEnrollments');
const offers=records.flatMap(record=>record.assignments.map(item=>({...item,sectionId:record.sectionId})));
ok(faculty.length===28&&new Set(faculty.map(item=>item.id)).size===28&&faculty.every(item=>/^\d{2}-\d{5}-\d{3}$/.test(item.id)),'28 teachers use unique NN-NNNNN-NNN IDs');
ok(new Set(sections.map(section=>section.program)).size===5&&sections.length===60&&students.length===1200,'five programs, 60 sections, and 1,200 students are seeded');
ok(['BSCS','BSIT','BSIS','BSGAMEDEV','BSANIMATION'].every(program=>[1,2,3,4].every(year=>sections.filter(section=>section.program===program&&section.yearLevel===year).length===3)),'every course and year level has three sections');
ok(sections.every(section=>section.capacity===50),'every seeded section has a 50-student capacity');
const curricula=r.read('curricula');
ok(curricula.filter(item=>item.program==='BSGAMEDEV').length===59&&curricula.filter(item=>item.program==='BSANIMATION').length===59,'complete BSEMC Game Development and Digital Animation curricula are seeded');
ok(curricula.some(item=>item.program==='BSGAMEDEV'&&item.yearLevel===4&&item.term==='second'&&item.subjectCode==='CEM4970'&&item.units===9),'BSEMC curriculum records retain year, term, subject, and unit data');
ok(students.every(item=>/^\d{4}-\d{5}$/.test(item.id)),'students use YYYY-NNNNN IDs');
ok(subjects.every(item=>/^[A-Z0-9-]+$/.test(item.code)),'subjects use normalized uppercase curriculum codes');
ok(new Set(offers.map(item=>item.id)).size===offers.length,'every section-subject offering has a unique ID');
ok(students.every(student=>{const section=sections.find(item=>item.id===student.sections[0]),expected=new Set(curricula.filter(item=>item.program===section.program&&Number(item.yearLevel)===section.yearLevel&&item.term==='first'&&item.status!=='archived'&&item.removed!==true).map(item=>item.subjectCode)),actual=new Set(enrollments.filter(item=>item.studentId===student.id).map(item=>item.subjectCode));return actual.size===expected.size&&[...expected].every(code=>actual.has(code))}),'every student receives the complete first-semester curriculum for their course and year');
ok(sections.every(section=>new Set(enrollments.filter(item=>item.sectionId===section.id).map(item=>item.studentId)).size<=section.capacity),'student enrollment never exceeds section capacity');
ok(enrollments.every(enrollment=>{const section=sections.find(item=>item.id===enrollment.sectionId);return curricula.some(item=>item.program===section.program&&Number(item.yearLevel)===section.yearLevel&&item.term==='first'&&item.subjectCode===enrollment.subjectCode)}),'no student is enrolled in second-semester or summer subjects');
ok(faculty.every(person=>offers.some(item=>item.facultyId===person.id)),'all seeded professors receive at least one first-semester offering');
ok(new Set(students.flatMap(item=>item.sections.map(section=>section.charAt(0)))).size===4,'students span all four year levels');
ok(sections.every(section=>/^\d(?:BSCS|BSIT|BSIS|BSGAMEDEV|BSANIMATION)-[1-3]$/.test(section.id)),'section IDs use year-course-section format for all five courses');
r.w.close();
const old={users:[{username:'admin',password:'admin123',role:'admin'}],faculty:[{id:'12-34567-890',last:'Reyes',first:'Maria'}],students:[{id:'2024-00001',last:'Dela Cruz',first:'Juan',sections:['BSCS-3A']}],subjects:[],demoCurriculumVersion:5,currentUser:{username:'admin',role:'admin'}};
const direct=load('admin.html',old);
ok(direct.read('students').length===1200&&direct.d.getElementById('countStudents').textContent==='1200','direct Admin refresh migrates and renders the latest demo data');
ok(/Every professor currently has an assigned subject/.test(direct.d.getElementById('unassignedFacultyTable').textContent),'Admin reports that every seeded professor has an assignment');
const demoUsers=direct.read('users'),demoAudit=direct.read('applicationAuditLog'),demoSubs=direct.read('studentSubmissions');
const demoExams=direct.read('exams'),demoQuestions=direct.read('questions'),demoEnrollments=direct.read('studentEnrollments');
const demoReports=direct.read('questionReports'),demoAnnouncements=direct.read('adminAnnouncements');
ok(['open','reviewed','resolved','dismissed'].every(status=>demoReports.some(report=>report.status===status)),'demo question reports cover open, reviewed, resolved, and dismissed statuses');
ok(['open','reviewed','resolved','dismissed'].every(status=>demoReports.filter(report=>report.status===status).length===3),'demo queue provides three examples under every report-status filter');
ok(demoAnnouncements.length>=2&&/Scheduled maintenance/.test(direct.d.querySelector('.header-inbox-panel')?.textContent||''),'Admin announcements are seeded and appear in the header inbox');
ok(demoUsers.find(user=>user.username==='2025-00002').password==='santos2025'&&demoUsers.find(user=>user.username==='23-32534-345').password==='reyes23','named Student and Faculty demo credentials are fixed');
const directRecords=direct.read('sectionSubjects'),directSubjects=direct.read('subjects');
const reyesOfferings=directRecords.flatMap(record=>(record.assignments||[]).map(item=>({...item,sectionId:record.sectionId}))).filter(item=>item.facultyId==='23-32534-345');
const santosCodes=new Set(demoEnrollments.filter(item=>item.studentId==='2025-00002').map(item=>item.subjectCode));
ok(new Set(reyesOfferings.map(item=>item.subjectCode)).size>=5&&new Set(reyesOfferings.map(item=>item.sectionId)).size>=5,'Maria Reyes handles several subjects across several sections');
ok(new Set(reyesOfferings.filter(item=>santosCodes.has(item.subjectCode)).map(item=>item.subjectCode)).size>=1,'Maria Reyes teaches a subject enrolled by Maria Santos');
const mariaSubs=demoSubs.filter(item=>item.studentId==='2025-00002');
ok(demoAudit.filter(item=>item.actorId==='2025-00002').length>=3,'demo student retains realistic activity history');
ok(demoAudit.filter(item=>item.actorId==='23-32534-345').length>=5,'demo faculty has login, exam, publish, and grading activity');
const offeredCodes=new Set(directRecords.flatMap(record=>record.assignments.map(item=>item.subjectCode)));
ok(directSubjects.filter(subject=>offeredCodes.has(subject.code)).every(subject=>{const count=demoExams.filter(exam=>exam.subjectCode===subject.code).length;return count>=1&&count<=4;}),'every offered subject has one to four assessments, including shared curriculum codes');
const timedExams=demoExams.filter(exam=>exam.durationMinutes>0);
ok(timedExams.every(exam=>exam.durationMinutes>=30&&exam.durationMinutes<=120)&&new Set(timedExams.map(exam=>exam.durationMinutes)).size===6,'timed assessment durations vary from 30 minutes to two hours');
const scheduledExams=demoExams.filter(exam=>exam.date);
const pastScheduled=scheduledExams.filter(exam=>exam.date<='2026-08-31'),movedToNextWeek=scheduledExams.filter(exam=>exam.date>='2026-09-07'&&exam.date<='2026-09-13');
ok(pastScheduled.length>=2&&movedToNextWeek.length>0&&scheduledExams.every(exam=>exam.date>='2026-08-18'&&exam.date<='2026-09-24'),'old schedules move to next week while deliberate past examples remain');
ok(demoExams.every(exam=>{const count=demoQuestions.filter(question=>question.examId===exam.id).length;return count>=5&&count<=20;}),'every assessment contains five to twenty short items');
ok(new Set(demoQuestions.map(question=>question.type)).size===6,'questions cover choice, true/false, number, fill-blank, matching, and essay formats');
const mistakesDemo=demoExams.find(exam=>exam.id==='DEMO-REVIEW-MISTAKES');
ok(mistakesDemo&&mistakesDemo.date>='2026-09-07'&&mistakesDemo.date<='2026-09-13','the previous review demo is rescheduled into next week');
const liveDemo=demoExams.find(exam=>exam.title.includes('Live Demo Quiz'));
ok(!liveDemo||liveDemo.durationMinutes===30,'any live demonstration assessment retains its short duration');
const alwaysOpen=demoExams.find(exam=>exam.id==='DEMO-ALWAYS-OPEN');
ok(alwaysOpen&&alwaysOpen.maxAttempts===99&&!alwaysOpen.date&&!alwaysOpen.end&&demoQuestions.filter(question=>question.examId===alwaysOpen.id).length===10,'Student has a 99-attempt practice exam with no deadline');
const mariaRelevant=demoExams.filter(exam=>santosCodes.has(exam.subjectCode)),mariaMissed=mariaRelevant.filter(exam=>exam.date&&exam.date<='2026-08-31'&&!mariaSubs.some(submission=>submission.examId===exam.id));
ok(Array.isArray(mariaMissed),'named Student missed-assessment state can be calculated');
direct.w.close();
const retainedMariaCodes=[...santosCodes].slice(0,2);const staleStudentData={users:demoUsers,faculty:direct.read('faculty'),students:direct.read('students'),subjects:directSubjects,sections:direct.read('sections'),sectionSubjects:directRecords,studentEnrollments:demoEnrollments.filter(item=>item.studentId!=='2025-00002'||retainedMariaCodes.includes(item.subjectCode)),subjectAssignments:direct.read('subjectAssignments'),exams:demoExams,questions:demoQuestions,studentSubmissions:demoSubs,applicationAuditLog:demoAudit,demoCurriculumVersion:12,currentUser:{username:'2025-00002',role:'student'}};
const refreshedStudent=load('student.html',staleStudentData);
ok(refreshedStudent.d.getElementById('statSubjects').textContent===String(retainedMariaCodes.length),'direct Student refresh preserves server-owned enrollment data');
ok(Number(refreshedStudent.d.getElementById('statCompleted').textContent)>=0,'direct Student refresh preserves the supplied completed-exam state');
refreshedStudent.w.close();
const unifiedLogin=load('login.html',{users:[],faculty:[],students:[],subjects:[]});
ok(unifiedLogin.d.getElementById('username').value==='admin'&&unifiedLogin.d.getElementById('password').value==='admin123','Unified login prefills one role-neutral demo entry point');unifiedLogin.w.close();
const ignoredRoleQuery=load('login.html',{users:[],faculty:[],students:[],subjects:[]},{query:'?role=student'});
ok(ignoredRoleQuery.d.getElementById('username').value==='admin'&&!ignoredRoleQuery.d.body.dataset.role,'legacy role query no longer selects or recolors the login form');ignoredRoleQuery.w.close();
const currentDevice=load('login.html',{demoCurriculumVersion:24,users:[],faculty:[],students:[],subjects:[]});
ok(currentDevice.read('users').some(user=>user.username==='admin')&&currentDevice.read('users').some(user=>user.username==='23-32534-345'),'current-version devices repair missing Admin and Faculty demo accounts');currentDevice.w.close();
process.exit(0);
