const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== ADMIN STUDENT PROFILE. Identity, tabs, relationships, and statistics ===');
const seed=SEED();
seed.sections=[{id:'A',name:'Section A'}];
seed.sectionSubjects=[{sectionId:'A',subjectCodes:['SUB2']}];
seed.studentSubmissions=[{studentId:'S1',examId:'e1',submittedAt:'2026-08-20T10:00:00Z',total:10,answers:[{awarded:8,needsManualGrading:false}]}];
const r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
const link=r.d.querySelector('#studentTable .profile-row');
ok(!!link&&/Cruz, Juan/.test(link.textContent),'student row is a profile entry point');
link.querySelector('td').click();
ok(r.d.getElementById('studentProfileName').textContent==='Juan Cruz','profile identifies the selected student');
ok(r.d.getElementById('studentProfileAvatar').textContent==='JC','student profile shows a circular initials avatar');
ok(/Section A/.test(r.d.getElementById('studentProfileContent').textContent),'overview shows section membership');
ok(/Maria Reyes/.test(r.d.getElementById('studentProfileContent').textContent)&&/Jose Santos/.test(r.d.getElementById('studentProfileContent').textContent),'overview shows direct and inherited professors');
ok(/2Subjects/.test(r.d.getElementById('studentProfileContent').textContent.replace(/\s/g,'')),'statistics include inherited and direct subjects');
r.w.showStudentProfileTab('history');
ok(/F1 Exam/.test(r.d.getElementById('studentProfileContent').textContent),'History tab shows exam activity');
r.w.showStudentProfileTab('grades');
ok(/8 \/ 10/.test(r.d.getElementById('studentProfileContent').textContent)&&/90%/.test(r.d.getElementById('studentProfileContent').textContent),'Grades tab shows score and converted grade');
ok(r.d.querySelector('[data-profile-tab="grades"]').classList.contains('active'),'selected tab has active state');
r.w.showStudentProfileTab('activity');
ok(/No recorded student actions|submit/.test(r.d.getElementById('studentProfileContent').textContent),'Actions tab is available');
r.w.showStudentProfileTab('login');
ok(/Recorded logins/.test(r.d.getElementById('studentProfileContent').textContent),'Login details tab is available');
r.w.close(); process.exit(0);
