const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== ADMIN STUDENT PROFILE. Identity, tabs, relationships, and statistics ===');
const seed=SEED();
seed.sections=[{id:'A',name:'Section A'}];
seed.subjects.push({code:'SUB3',name:'New Subject'});
seed.subjects.find(subject=>subject.code==='SUB2').yearLevel=1;
seed.subjects.find(subject=>subject.code==='SUB3').yearLevel=1;
seed.sectionSubjects=[{sectionId:'A',assignments:[{id:'O-SUB2-A',subjectCode:'SUB2',facultyId:'F2'},{id:'O-SUB3-A',subjectCode:'SUB3',facultyId:'F1'}]}];
seed.studentSubmissions=[{studentId:'S1',examId:'e1',submittedAt:'2026-08-20T10:00:00Z',total:10,answers:[{awarded:8,needsManualGrading:false}]}];
const r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
const link=[...r.d.querySelectorAll('#studentTable tr')].find(row=>/Cruz, Juan/.test(row.textContent));
ok(!!link&&!/Sections/.test(r.d.querySelector('#studentTable tr').textContent),'student table removes the Sections column');
const nameLink=link.querySelector('.student-name-link');
ok(nameLink?.getAttribute('aria-label')==='Manage Juan Cruz','student name cell is an accessible Manage student link');
nameLink.click();
ok(r.d.getElementById('studentEnrollmentModal').style.display==='flex'&&r.d.getElementById('studentEnrollmentName').textContent==='Juan Cruz','clicking the student name opens Manage student');
r.w.closeModal('studentEnrollmentModal');
link.querySelector('.section-action-trigger').click();
const actionLabels=[...link.querySelectorAll('.section-action-menu button span:last-child')].map(item=>item.textContent).join('|');
ok(actionLabels==='Edit|Manage student|Deactivate account|Delete','student settings actions use the requested order');
link.querySelectorAll('.section-action-menu button')[1].click();
ok(!link.querySelector('.section-action-menu').classList.contains('open'),'settings menu closes when its prompt opens');
ok(r.d.getElementById('studentEnrollmentName').textContent==='Juan Cruz','administrative view identifies the selected student');
ok(r.d.getElementById('studentEnrollmentAvatar').textContent==='JC','administrative view keeps the hero profile');
ok(!!r.d.querySelector('[data-command-tab="subjects"].active'),'administrative view keeps underline tabs');
ok(/Enrolled subjects/.test(r.d.getElementById('studentEnrollmentContent').textContent),'Subjects tab provides enrollment commands');
ok(!r.d.querySelector('.available-subjects').open,'available subjects are collapsed by default');
r.d.querySelector('.available-subjects').open=true;
const availableRow=[...r.d.querySelectorAll('.subject-only-table tbody tr[role="button"]')].find(row=>/SUB3/.test(row.textContent));
ok(!!availableRow&&!/SECTION|PROFESSOR/.test(r.d.querySelector('.subject-only-table thead').textContent),'available table lists subjects only');
availableRow.click();
ok(r.d.getElementById('studentSectionPickerModal').style.display==='flex'&&/Select a section/.test(r.d.getElementById('studentSectionPickerTitle').textContent),'clicking a subject opens the section picker');
const sectionChoice=r.d.querySelector('#studentSectionPickerOptions .student-section-choice');
ok(!!sectionChoice&&/Prof\./.test(sectionChoice.textContent),'section choice includes its professor');
sectionChoice.click(); r.w.applyStudentOffering();
ok(/SUB3/.test(r.d.querySelector('.subject-only-table tbody tr:first-child').textContent)&&/Ready to add/.test(r.d.querySelector('.subject-only-table tbody tr:first-child').textContent),'adding stages the subject at the top of table two');
ok(!/SUB3/.test(r.d.querySelector('.student-enrolled-table tbody').textContent),'adding in the prompt does not save the enrollment yet');
ok(/Savesubjects1/.test(r.d.querySelector('.batch-enrollment-actions').textContent.replace(/\s/g,'')),'table two provides one styled batch save button and count badge');
r.w.saveStudentEnrollmentBatch();
ok(/SUB3/.test(r.d.querySelector('.student-enrolled-table tbody').textContent)&&/Prof\. Maria Reyes/.test(r.d.querySelector('.student-enrolled-table tbody').textContent),'batch save moves subject, section, and professor into table one');
ok(/Automatically add subjects/.test(r.d.querySelector('.batch-enrollment-actions').textContent),'table two provides automatic curriculum selection');
r.w.automaticallyAddStudentSubjects();
ok(/SUB2/.test(r.d.querySelector('.subject-only-table tbody tr:first-child').textContent)&&/Ready to add/.test(r.d.querySelector('.subject-only-table tbody tr:first-child').textContent),'automatic add stages matching year-level section subjects without saving them');
ok(/Edit student/.test(r.d.querySelector('.student-command-menu').textContent)&&/Deactivate account/.test(r.d.querySelector('.student-command-menu').textContent),'three-dot menu exposes named administrative actions');
r.w.showStudentCommandTab('grades');
ok(/8 \/ 10/.test(r.d.getElementById('studentEnrollmentContent').textContent)&&/90%/.test(r.d.getElementById('studentEnrollmentContent').textContent),'administrative tabs retain grades');
ok(r.d.querySelector('[data-command-tab="grades"]').classList.contains('active'),'selected administrative tab has active state');
r.w.openAcademicProfileFromEnrollment();
ok(r.d.getElementById('studentProfileName').textContent==='Juan Cruz','read-only academic profile remains separate');
const relationshipTable=r.d.querySelector('.profile-relationship-table');
ok(relationshipTable&&[...relationshipTable.querySelectorAll('th')].map(cell=>cell.textContent.trim()).join('|')==='Subject code|Subject name|Section|Professor','read-only overview combines subject relationships into one table');
ok(!r.d.querySelector('#studentProfileContent .profile-columns')&&/SUB3/.test(relationshipTable.textContent)&&/A/.test(relationshipTable.textContent),'read-only overview removes the separate section card and shows each subject section');
ok(/Prof\./.test(r.d.getElementById('studentProfileContent').textContent),'read-only overview continues to show professor relationships');
r.w.close(); process.exit(0);
