const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== ADMIN TABLE TOOLS. Search, sort, group, direction, navigation ===');
const seed=SEED(); seed.faculty.push({id:'F0',last:'Adams',first:'Zoe'});
for(let i=3;i<=14;i++)seed.faculty.push({id:`F${i}`,last:`Person ${i}`,first:`Name ${i}`});
const r=load('admin.html',{...seed,currentUser:{username:'admin',role:'admin'}});
ok(r.d.querySelectorAll('.table-tools').length===6,'tools are mounted for all six Admin data views');
const tools=r.d.querySelector('[data-table-tools="faculty"]'), table=r.d.getElementById('facultyTable');
ok(!!tools.querySelector('.table-search-toggle')&&!!tools.querySelector('.table-sort-toggle')&&!!tools.querySelector('.table-group-toggle'),'search, sort, and group icons exist');
tools.querySelector('.table-search-toggle').click(); tools.querySelector('.table-sort-toggle').click();
ok(!tools.querySelector('.table-sort-toggle').classList.contains('active')===false&&tools.querySelector('.table-search-box').hidden,'opening Sort closes and deactivates Search');
tools.querySelector('.table-sort-toggle').click();
tools.querySelector('.table-search-toggle').click(); const search=tools.querySelector('input[type="search"]'); search.value='Adams'; search.dispatchEvent(new r.w.Event('input',{bubbles:true}));
ok([...table.querySelectorAll('tr')].filter(row=>!row.hidden).some(row=>/Adams/.test(row.textContent)),'search finds a surname');
ok([...table.querySelectorAll('tr')].filter(row=>!row.hidden).every(row=>row.rowIndex===0||/Adams/.test(row.textContent)),'search hides nonmatches');
search.value=''; search.dispatchEvent(new r.w.Event('input',{bubbles:true}));
ok([...table.querySelectorAll('tr')].slice(1).every(row=>!row.hidden),'all matching rows remain available in one continuous scroll');
const sort=tools.querySelector('.sort-field select'); sort.value='1'; sort.dispatchEvent(new r.w.Event('change',{bubbles:true}));
ok(/Adams/.test([...table.querySelectorAll('tr')].find(row=>row.rowIndex>0&&!row.hidden).textContent),'sort by surname orders ascending');
tools.querySelector('.table-direction').click();
ok(!/Adams/.test([...table.querySelectorAll('tr')].find(row=>row.rowIndex>0&&!row.hidden).textContent),'direction icon reverses the order');
ok(tools.querySelector('.table-direction').classList.contains('descending'),'direction icon transforms to its descending state');
const group=tools.querySelector('.group-field select'); group.value='1'; group.dispatchEvent(new r.w.Event('change',{bubbles:true}));
ok(table.querySelectorAll('.table-group-row').length>0,'group selector inserts labelled groups');
ok([...table.querySelectorAll('.table-group-row')].every(row=>/record/.test(row.textContent)),'every group heading shows its total count');
ok([...group.options].some(option=>/Alphabetically/.test(option.textContent)),'surname tables offer alphabetical initial grouping');
ok(!tools.querySelector('.table-prev')&&!tools.querySelector('.table-next')&&!tools.querySelector('.table-page-status'),'pagination is removed for continuous scrolling');
r.w.close(); process.exit(0);
