const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
console.log('=== OO. Section assignment replaces direct Student allotment UI ===');
const s=SEED();
s.subjectAssignments=[{subjectCode:'SUB1',facultyIds:['F1','F2']},{subjectCode:'SUB2',facultyIds:['F2']}];
s.sections=[{id:'1BSCS-1',name:'Section A',program:'BSCS',yearLevel:1}]; s.sectionSubjects=[{sectionId:'1BSCS-1',subjectCodes:['SUB2']}]; s.allotments=[];
s.students[0].sections=['1BSCS-1'];
s.curricula=[{program:'BSCS',yearLevel:1,term:'first',subjectCode:'SUB1',subjectName:'HCI',units:3,status:'active'},{program:'BSCS',yearLevel:1,term:'first',subjectCode:'SUB2',subjectName:'SE',units:3,status:'active'}];
let r=load('admin.html',{...s,currentUser:{username:'admin',role:'admin'}});
ok(!r.d.getElementById('allotmentSection'),'obsolete allotment workspace is absent');
ok(!!r.d.getElementById('sectionSection'),'Section workspace is the enrolment route');
r.w.openSectionSubjects(0);
ok(/SUB1/.test(r.d.getElementById('sectionSubjects').textContent)&&/SUB2/.test(r.d.getElementById('sectionSubjects').textContent),'Section receives its subjects from Load Management');
r.w.close();
let st=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
ok(/SUB2/.test(st.d.querySelector('#subjectsTable tbody').textContent),'Student receives the section subject');
st.w.close(); process.exit(0);
