const {load,SEED}=require('./harness');
const ok=(c,m)=>console.log(`  ${c?'✅':'❌'} ${m}`);
const today=new Date().toLocaleDateString('en-CA');

(async()=>{
console.log('=== TRUE/FALSE. Authoring through automatic grading ===');
let s=SEED();
let r=load('faculty.html',{...s,currentUser:{username:'F1',role:'faculty'}});
r.w.manageQuestions('e1');
r.w.openQuestionModal();
r.d.getElementById('questionText').value='The Earth orbits the Sun.';
const type=r.d.getElementById('questionType');
type.value='truefalse';
await r.w.requestQuestionTypeChange('truefalse');
ok(r.d.getElementById('trueFalseSection').style.display==='block','True/False settings appear only for that type');
ok(r.d.getElementById('mcqOptions').style.display==='none','configurable MCQ choices are hidden');
r.d.getElementById('trueFalseAnswer').value='false';
r.w.saveQuestion();
const question=r.read('questions').find(q=>q.text==='The Earth orbits the Sun.');
ok(question.type==='truefalse','question persists with True/False type');
ok(question.options.length===2 && question.options[1].isCorrect,'fixed choices preserve the configured correct answer');
r.w.editQuestion(question.id);
ok(r.d.getElementById('trueFalseAnswer').value==='false','correct answer restores when editing');
r.w.closeQuestionModal();

console.log('\n=== NUMBER. Accepted value and tolerance ===');
r.w.openQuestionModal();
r.d.getElementById('questionText').value='What is the measured value?';
const numberType=r.d.getElementById('questionType');
numberType.value='number';
await r.w.requestQuestionTypeChange('number');
ok(r.d.getElementById('numberAnswerSection').style.display==='block','numeric settings appear for Number type');
r.d.getElementById('numberAcceptedValue').value='10';
r.d.getElementById('numberTolerance').value='-1';
r.w.saveQuestion();
ok(!r.read('questions').some(q=>q.type==='number'),'negative tolerance is rejected');
r.d.getElementById('numberTolerance').value='0.5';
r.w.saveQuestion();
const numeric=r.read('questions').find(q=>q.type==='number');
ok(numeric.acceptedValue===10 && numeric.tolerance===0.5,'numeric grading settings persist as numbers');
ok(r.w.numericAnswerIsCorrect('10.5',10,0.5),'upper tolerance boundary is accepted');
ok(!r.w.numericAnswerIsCorrect('10.51',10,0.5),'value outside tolerance is rejected');

console.log('\n=== FILL BLANK. Prompt marker and matching rules ===');
r.w.openQuestionModal();
r.d.getElementById('questionText').value='The capital is Manila.';
const fillType=r.d.getElementById('questionType');
fillType.value='fillblank';
await r.w.requestQuestionTypeChange('fillblank');
r.d.getElementById('expectedAnswer').value='Manila';
r.w.saveQuestion();
ok(!r.read('questions').some(q=>q.type==='fillblank'),'prompt without underline marker is rejected');
r.d.getElementById('questionText').value='The capital is ___.';
r.d.getElementById('answerCaseSensitive').checked=false;
r.d.getElementById('answerWhitespaceSensitive').checked=false;
r.d.getElementById('answerSymbolSensitive').checked=false;
r.w.saveQuestion();
const fillblank=r.read('questions').find(q=>q.type==='fillblank');
ok(fillblank.expectedAnswer==='Manila','fill-in answer key persists');
ok(r.w.textAnswerIsCorrect('  MANILA! ',fillblank.expectedAnswer,fillblank),'disabled sensitivities normalize the response');
ok(!r.w.textAnswerIsCorrect('Cebu',fillblank.expectedAnswer,fillblank),'different text remains incorrect');

console.log('\n=== MATCHING. Pair authoring and automatic grading ===');
r.w.openQuestionModal();
r.d.getElementById('questionText').value='Match each country to its capital.';
const matchingType=r.d.getElementById('questionType');
matchingType.value='matching';
await r.w.requestQuestionTypeChange('matching');
let rows=[...r.d.querySelectorAll('#matchingPairs .matching-pair')];
rows[0].querySelector('.matching-left').value='Philippines';
rows[0].querySelector('.matching-right').value='Manila';
rows[1].querySelector('.matching-left').value='Japan';
rows[1].querySelector('.matching-right').value='Manila';
r.w.saveQuestion();
ok(!r.read('questions').some(q=>q.type==='matching'),'duplicate matching answers are rejected');
rows[1].querySelector('.matching-right').value='Tokyo';
r.w.saveQuestion();
const matching=r.read('questions').find(q=>q.type==='matching');
ok(matching.pairs.length===2 && matching.pairs[1].right==='Tokyo','complete unique pairs persist');
ok(r.w.matchingAnswerIsCorrect([0,1],matching.pairs),'correct mapping is recognized');
ok(!r.w.matchingAnswerIsCorrect([1,0],matching.pairs),'swapped mapping is rejected');

console.log('\n=== IMAGE DRAG. Accessible drag/drop with select fallback ===');
r.w.openQuestionModal();
r.d.getElementById('questionText').value='Place each label on the diagram.';
const dragType=r.d.getElementById('questionType');
dragType.value='imagedrag';
await r.w.requestQuestionTypeChange('imagedrag');
rows=[...r.d.querySelectorAll('#matchingPairs .matching-pair')];
rows[0].querySelector('.matching-left').value='Left label'; rows[0].querySelector('.matching-right').value='Left target';
rows[1].querySelector('.matching-left').value='Right label'; rows[1].querySelector('.matching-right').value='Right target';
r.w.saveQuestion();
ok(!r.read('questions').some(q=>q.type==='imagedrag'),'image drag question is rejected without an image');
r.d.getElementById('questionImageUrl').value='https://example.com/diagram.png';
r.d.getElementById('questionImageAlt').value='Diagram with left and right target areas';
r.w.saveQuestion();
const imageDrag=r.read('questions').find(q=>q.type==='imagedrag');
ok(imageDrag.pairs.length===2 && imageDrag.imageAlt,'image drag configuration persists');
r.w.close();

s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
s.questions=[question];
r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
ok(/True or false/.test(r.d.querySelector('.q-type').textContent),'Student sees the correct question-type label');
const answer=r.d.querySelector(`input[name="q_${question.id}"][value="1"]`);
answer.checked=true;
answer.dispatchEvent(new r.w.Event('change',{bubbles:true}));
r.w.captureAllVisible();
r.w.persistAttempt();
ok(r.read('examAttempts')['S1::e1'].answers[question.id].type==='truefalse','True/False answer autosaves with its type');
r.w.reviewAnswers();
await r.w.submitExamAnswers();
const submission=r.read('studentSubmissions')[0];
ok(submission.answers[0].isCorrect && submission.answers[0].awarded===question.points,'correct answer is graded automatically');
r.w.close();

s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
s.questions=[numeric];
r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
const numericInput=r.d.querySelector('.numeric-ans-input');
ok(numericInput?.type==='number','Student receives a numeric input');
numericInput.value='9.5';
numericInput.dispatchEvent(new r.w.Event('input',{bubbles:true}));
r.w.captureAllVisible();
r.w.persistAttempt();
ok(r.read('examAttempts')['S1::e1'].answers[numeric.id].response==='9.5','numeric response autosaves');
r.w.reviewAnswers();
await r.w.submitExamAnswers();
const numericSubmission=r.read('studentSubmissions')[0];
ok(numericSubmission.answers[0].isCorrect && numericSubmission.answers[0].awarded===numeric.points,'numeric boundary answer is graded automatically');
r.w.close();

s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
s.questions=[fillblank];
r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
const blankInput=r.d.querySelector('.fillblank-ans-input');
ok(blankInput?.type==='text','Student receives a focused fill-in input');
ok(blankInput.classList.contains('short-ans-input')&&!blankInput.matches('textarea'),'fill-in answer remains a compact single-line field');
blankInput.value='manila!';
blankInput.dispatchEvent(new r.w.Event('input',{bubbles:true}));
r.w.captureAllVisible();
r.w.persistAttempt();
ok(r.read('examAttempts')['S1::e1'].answers[fillblank.id].response==='manila!','fill-in response autosaves');
r.w.reviewAnswers();
await r.w.submitExamAnswers();
const fillSubmission=r.read('studentSubmissions')[0];
ok(fillSubmission.answers[0].isCorrect && fillSubmission.answers[0].awarded===fillblank.points,'matching rules are applied during submission');
r.w.close();

s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
s.questions=[matching];
r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
const matchInputs=[...r.d.querySelectorAll('.matching-answer')];
ok(matchInputs.length===2,'Student receives one selector per matching item');
matchInputs[0].value='0'; matchInputs[1].value='1';
matchInputs.forEach(input=>input.dispatchEvent(new r.w.Event('change',{bubbles:true})));
r.w.captureAllVisible(); r.w.persistAttempt();
ok(r.read('examAttempts')['S1::e1'].answers[matching.id].matches.join(',')==='0,1','matching selections autosave together');
r.w.reviewAnswers();
ok(/Philippines.*Manila/.test(r.d.getElementById('examReviewSection').textContent),'review shows the selected pairings');
await r.w.submitExamAnswers();
const matchingSubmission=r.read('studentSubmissions')[0];
ok(matchingSubmission.answers[0].isCorrect && matchingSubmission.answers[0].awarded===matching.points,'complete correct mapping is graded automatically');
r.w.close();

s=SEED();
s.exams=[{...s.exams[0],date:today,start:'00:01',end:'23:59'}];
s.questions=[imageDrag];
r=load('student.html',{...s,currentUser:{username:'S1',role:'student'}});
r.w.startExam('e1');
const tokens=[...r.d.querySelectorAll('.drag-token')];
const targets=[...r.d.querySelectorAll('.drop-target')];
ok(tokens.length===2 && targets.length===2,'Student receives draggable labels and drop targets');
ok(targets.every(target=>target.querySelector('select')),'every target includes a native select fallback');
tokens[0].click(); targets[0].click(); tokens[1].click(); targets[1].click();
r.w.captureAllVisible(); r.w.persistAttempt();
ok(r.read('examAttempts')['S1::e1'].answers[imageDrag.id].matches.join(',')==='0,1','touch/keyboard selection updates shared answer state');
r.w.reviewAnswers();
ok(/Left label.*Left target/.test(r.d.getElementById('examReviewSection').textContent),'review describes placed labels');
await r.w.submitExamAnswers();
const dragSubmission=r.read('studentSubmissions')[0];
ok(dragSubmission.answers[0].isCorrect && dragSubmission.answers[0].awarded===imageDrag.points,'correct placements are graded automatically');
r.w.close();
process.exit(0);
})();
